import { useEffect, useRef, useState } from 'react';
import { Check, Code2, Plus, Save, Upload, Sparkles, Trash2, X } from 'lucide-react';
import { Button, IconButton, SegmentedControl, SelectField, SliderField, TextAreaField, TextField } from '../../ui';
import { VOX_ANIMATION_CATEGORIES, VOX_TEMPLATES, createVoxAnimation, validateVoxAnimation, voxTemplate, voxItemSchema, type VoxAnimation, type VoxAnimationProps, type VoxSavedTemplate } from '../../shared/vox-animation';
import type { VoxApi, VoxLocalAsset } from './VoxAnimationPreview';
import './vox-animation.css';

export function VoxAnimationEditor({shotId,animation,title,subtitle,api,assets,ratio,durationMs,busy,onChange,onImportAsset,previewReady,onExport,onCancelExport}:{shotId:string;animation?:VoxAnimation;title:string;subtitle:string;api:VoxApi;assets:readonly VoxLocalAsset[];ratio:string;durationMs:number;busy:boolean;previewReady?:boolean;onExport?:()=>Promise<boolean>;onCancelExport?:()=>Promise<void>;onChange:(a:VoxAnimation)=>void;onImportAsset?:(kind:'image'|'audio')=>Promise<void>}){
  const value=animation??createVoxAnimation(title,subtitle),p=value.template.props,t=voxTemplate(value.template.id)!;
  const [catalogOpen,setCatalogOpen]=useState(false),[exporting,setExporting]=useState(false);
  const [category,setCategory]=useState('全部'),[search,setSearch]=useState(''),[saved,setSaved]=useState<VoxSavedTemplate[]>([]),[name,setName]=useState(''),[showCode,setShowCode]=useState(false),[running,setRunning]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const latest=useRef(value);latest.current=value;const request=useRef('');const mounted=useRef(true);
  useEffect(()=>{mounted.current=true;void api.listVoxTemplates().then(setSaved).catch(e=>setError(String(e)));return()=>{mounted.current=false;if(request.current)void api.cancelVoxAnimation(request.current);};},[api]);
  const update=(patch:Partial<VoxAnimationProps>)=>onChange({...value,template:{...value.template,props:{...p,...patch}}});
  const choose=(id:string)=>{onChange({...value,mode:'template',template:{id,props:p}});setCatalogOpen(false);setMessage('');setError('');};
  async function compile(){setError('');setRunning(true);const id=crypto.randomUUID();request.current=id;const source=latest.current.code.source;try{const result=await api.compileVoxAnimation(source);if(mounted.current&&request.current===id&&latest.current.code.source===source){onChange({...latest.current,mode:'code',code:{...latest.current.code,...result}});setMessage('代码编译通过，预览中可检查实际画面');}}catch(e){if(mounted.current)setError(String(e));}finally{if(request.current===id){request.current='';if(mounted.current)setRunning(false);}}}
  async function generate(){setError('');setRunning(true);const snapshot=JSON.stringify(latest.current),id=crypto.randomUUID();request.current=id;try{const a=latest.current;const result=await api.generateVoxAnimation({requestId:id,prompt:a.code.prompt,source:a.code.source,templateId:a.template.id,props:a.template.props,ratio,durationMs});if(mounted.current&&request.current===id){if(JSON.stringify(latest.current)!==snapshot){setError('生成期间内容已修改，本次结果未覆盖当前草稿');return;}onChange({...latest.current,mode:'code',code:{...latest.current.code,...result}});setMessage('动画代码已生成，可继续描述修改或保存为个人模板');}}catch(e){if(mounted.current&&request.current===id)setError(String(e));}finally{if(request.current===id){request.current='';if(mounted.current)setRunning(false);}}}
  async function saveTemplate(){setError('');try{if(!previewReady)throw new Error('请先修正内容并等待动画预览成功');const issues=validateVoxAnimation(value,assets);if(issues.length)throw new Error(issues.join('；'));if(!name.trim())throw new Error('请填写个人模板名称');setSaved(await api.saveVoxTemplate({id:crypto.randomUUID(),name:name.trim(),animation:value,updatedAt:new Date().toISOString()}));setName('');setMessage('已保存到我的模板');}catch(e){setError(String(e));}}
  const filtered=VOX_TEMPLATES.filter(x=>(category==='全部'||x.category===category)&&`${x.name}${x.description}`.includes(search));
  const images=assets.filter(x=>x.kind==='image'),audios=assets.filter(x=>x.kind==='audio');
  return <fieldset disabled={busy} className="vox-editor" aria-label="动画模板与 AI 创作">
    <SegmentedControl label="动画创作方式" value={value.mode} options={[{value:'template',label:'动画模板'},{value:'code',label:'AI 生成动画'}]} onChange={mode=>onChange({...value,mode})}/>
    {value.mode==='template'?<>
      <Button variant="secondary" onClick={()=>setCatalogOpen(x=>!x)} aria-expanded={catalogOpen}>选择模板 · {t?.name??'未选择'}</Button>
      {catalogOpen?<>
      <div className="vox-catalog-filters"><SelectField label="模板分类" value={category} options={[{value:'全部',label:`全部 · ${VOX_TEMPLATES.length}`},...VOX_ANIMATION_CATEGORIES.map(x=>({value:x,label:x})),{value:'我的模板',label:'我的模板'}]} onChange={e=>setCategory(e.target.value)}/><TextField label="搜索模板" value={search} onChange={(_,d)=>setSearch(d.value)}/></div>
      {category==='我的模板'?<div className="vox-template-list">{saved.filter(x=>x.name.includes(search)).map(x=><div key={x.id} className="vox-saved-row"><Button variant="subtle" onClick={()=>onChange(x.animation)}>{x.name}</Button><IconButton label={`删除模板 ${x.name}`} icon={<Trash2 size={14}/>} onClick={()=>void api.deleteVoxTemplate(x.id).then(setSaved).catch(e=>setError(String(e)))}/></div>)}{saved.length===0?<p className="vox-hint">将编辑好的动画保存为个人模板后，会显示在这里。</p>:null}</div>:<div className="vox-template-list" role="group" aria-label="可用动画模板">{filtered.map(x=><Button key={x.id} variant={x.id===t?.id?'secondary':'subtle'} aria-pressed={x.id===t?.id} className="vox-template-option" onClick={()=>choose(x.id)}><span><strong>{x.name}</strong><small>{x.description}</small></span>{x.id===t?.id?<Check size={14}/>:null}</Button>)}{filtered.length===0?<p>没有匹配的模板</p>:null}</div>}
      </>:null}
    </>:<div className="vox-ai-controls"><TextAreaField label="描述动画或继续修改" value={value.code.prompt} onChange={(_,d)=>onChange({...value,code:{...value.code,prompt:d.value}})} resize="vertical" placeholder="例如：标题从左侧进入，三个观点依次展开，使用纸张质感"/><p className="vox-hint">使用系统设置中的文本模型，按该服务实际用量计费。图片和数据取自下方已选内容。</p><div className="vox-row"><Button variant="primary" disabled={busy||running||!value.code.prompt.trim()} onClick={()=>void generate()}><Sparkles size={14}/>{running?'正在生成…':value.code.source?'按要求修改':'生成动画'}</Button>{running?<Button onClick={()=>{const id=request.current;request.current='';if(id)void api.cancelVoxAnimation(id).catch(()=>{});setRunning(false);setMessage('已取消生成');}}><X size={14}/>取消</Button>:null}<Button variant="subtle" onClick={()=>setShowCode(x=>!x)}><Code2 size={14}/>{showCode?'收起代码':'查看代码'}</Button></div>{showCode?<><TextAreaField label="动画 TSX 代码" value={value.code.source} onChange={(_,d)=>onChange({...value,code:{...value.code,source:d.value,compiled:''}})} resize="vertical" fieldClassName="vox-code"/><Button disabled={running||busy||!value.code.source.trim()} onClick={()=>void compile()}>检查代码并预览</Button></>:null}</div>}
    <div className="vox-section-heading"><strong>{t?.name??'动画'} · 内容</strong><small>修改后更新中央预览</small></div>
    <TextField label="动画标题" value={p.title} onChange={(_,d)=>update({title:d.value})}/><TextAreaField label="正文 / 补充说明" value={p.subtitle} onChange={(_,d)=>update({subtitle:d.value})} resize="vertical"/>
    <div className="vox-two-col">{['book','evidence','label'].includes(t?.kind??'')?<TextField label="作者 / 人物" value={p.author} onChange={(_,d)=>update({author:d.value})}/>:null}{t?.numeric||t?.id==='compare-values'?<TextField label="数据单位" value={p.unit} onChange={(_,d)=>update({unit:d.value})}/>:null}</div>
    <TextField label="来源 / 页码" value={p.source} onChange={(_,d)=>update({source:d.value})}/>{['evidence','text','book'].includes(t?.kind??'')?<TextField label="强调词（逗号分隔）" value={p.highlight} onChange={(_,d)=>update({highlight:d.value})}/>:null}
    <div className="vox-colors">{(['accent','background','foreground'] as const).map((key,i)=><TextField key={key} label={['强调色','背景色','文字色'][i]} placeholder="#c7513b" value={p[key]} onChange={(_,d)=>update({[key]:d.value})}/>)}</div>
    {t?.items?<><div className="vox-section-heading"><strong>{t.map?'地点与路线':'内容条目'}</strong><Button density="compact" variant="subtle" disabled={p.items.length>=(t.maxItems??24)} onClick={()=>update({items:[...p.items,voxItemSchema.parse({label:''})]})}><Plus size={13}/>添加</Button></div>{p.items.map((item,i)=><div className="vox-item" key={i}><div className="vox-row"><strong>{i+1}</strong><IconButton label={`删除条目 ${i+1}`} icon={<Trash2 size={13}/>} onClick={()=>update({items:p.items.filter((_,j)=>i!==j)})}/></div><TextField label={t.map?`地点 ${i+1}`:`条目 ${i+1}`} value={item.label} onChange={(_,d)=>update({items:p.items.map((x,j)=>i===j?{...x,label:d.value}:x)})}/><TextField label={`说明 ${i+1}`} value={item.detail} onChange={(_,d)=>update({items:p.items.map((x,j)=>i===j?{...x,detail:d.value}:x)})}/>{t.numeric||t.id==='compare-values'||t.id==='time-year-counter'?<TextField label={`数值 ${i+1}`} type="number" value={String(item.value)} onChange={(_,d)=>{const n=Number(d.value);if(Number.isFinite(n))update({items:p.items.map((x,j)=>i===j?{...x,value:n}:x)});}}/>:null}{t.kind==='timeline'||t.kind==='book'||t.map||t.id==='data-ranking'?<TextField label={`日期 / 章节 ${i+1}`} value={item.date} onChange={(_,d)=>update({items:p.items.map((x,j)=>i===j?{...x,date:d.value}:x)})}/>:null}{t.map?<div className="vox-two-col">{(['lng','lat'] as const).map(k=><TextField key={k} label={`${k==='lng'?'经度':'纬度'} ${i+1}`} type="number" step={.001} value={String(item[k])} onChange={(_,d)=>{const n=Number(d.value);if(Number.isFinite(n)&&Math.abs(n)<=(k==='lng'?180:90))update({items:p.items.map((x,j)=>i===j?{...x,[k]:n}:x)});}}/>)}</div>:null}</div>)}</>:null}
    <div className="vox-section-heading"><strong>图片素材</strong><small>顺序决定图层 / 书页顺序</small></div>
    {p.assetIds.map((id,i)=><div className="vox-asset-row" key={i}><SelectField label={`图片 ${i+1}${t?.id==='book-3d'?(i?' · 内页':' · 封面'):''}`} value={id} options={[...(images.some(a=>a.id===id)?[]:[{value:id,label:'素材不在当前项目，请重新选择'}]),...images.map(a=>({value:a.id,label:a.label}))]} onChange={e=>update({assetIds:p.assetIds.map((x,j)=>i===j?e.target.value:x)})}/><IconButton label={`移除图片 ${i+1}`} icon={<X size={13}/>} onClick={()=>update({assetIds:p.assetIds.filter((_,j)=>j!==i)})}/></div>)}
    <Button density="compact" variant="secondary" disabled={!images.length||p.assetIds.length>=(t?.maxImages??24)} onClick={()=>update({assetIds:[...p.assetIds,images.find(a=>!p.assetIds.includes(a.id))?.id??images[0].id]})}><Plus size={13}/>添加项目图片</Button>{onImportAsset?<Button density="compact" disabled={busy} onClick={()=>void onImportAsset('image').catch(e=>setError(String(e)))}><Upload size={14}/>导入图片</Button>:null}{!images.length?<p className="vox-hint">导入书封、截图或透明 PNG，按所选模板的顺序添加。</p>:null}
    {t?.audio?<><SelectField label="频谱 / 波形音频" value={p.audioAssetId??''} options={[{value:'',label:'请选择音频'},...audios.map(a=>({value:a.id,label:a.label}))]} onChange={e=>update({audioAssetId:e.target.value||undefined})}/>{onImportAsset?<Button onClick={()=>void onImportAsset('audio').catch(e=>setError(String(e)))}><Upload size={14}/>导入音频到时间线</Button>:null}<p className="vox-hint">此处选择分析音源；实际声音由声音面板的时间线混音输出。</p></>:null}
    {t?.map?<TextAreaField label="区域 GeoJSON（地区聚焦必填）" value={p.geoJson} resize="vertical" onChange={(_,d)=>update({geoJson:d.value})} hint="默认使用本地世界底图；区域与历史路线请填写真实数据。"/>:null}
    {t?.id==='evidence-focus'||t?.id==='transition-zoom'?<div>{(['x','y','width','height'] as const).map((k,i)=><SliderField key={k} label={['焦点横向位置','焦点纵向位置','区域宽度','区域高度'][i]} min={i>1?5:0} max={100} value={Math.round(p.focus[k]*100)} valueLabel={`${Math.round(p.focus[k]*100)}%`} onChange={(_,d)=>update({focus:{...p.focus,[k]:Number(d.value)/100}})}/>)}</div>:null}
    <div className="vox-save-template"><TextField label="保存为我的模板" value={name} placeholder="模板名称" onChange={(_,d)=>setName(d.value)}/><Button disabled={busy||running||!previewReady} onClick={()=>void saveTemplate()}><Save size={14}/>保存模板</Button></div>
    {onExport?<div className="vox-row"><Button disabled={busy||running||exporting||!previewReady} onClick={async()=>{setExporting(true);setError('');try{const saved=await onExport();if(mounted.current)setMessage(saved?'镜头已导出，已打开所在文件夹':'已取消选择导出位置');}catch(e){if(mounted.current)setError(String(e));}finally{if(mounted.current)setExporting(false);}}}>{exporting?'正在导出镜头…':'导出此镜头'}</Button>{exporting&&onCancelExport?<Button onClick={()=>void onCancelExport()}>取消导出</Button>:null}</div>:null}
    {error?<p role="alert" className="vox-error">{error}</p>:null}{message?<p role="status" className="vox-hint">{message}</p>:null}
  </fieldset>;
}
