import React, { type CSSProperties } from 'react';
import { AbsoluteFill, Img, interpolate, spring, useCurrentFrame, useVideoConfig } from 'remotion';
import { visualizeAudio, type MediaUtilsAudioData } from '@remotion/media-utils';
import type { VoxAnimationPayload, VoxAnimationProps } from '../../shared/vox-animation';
import worldMap from './world-map.json';
import { shotcraftRecipe } from '../../shared/shotcraft-recipes';
import { ShotcraftComposition } from './shotcraft/ShotcraftComposition';

const clamp=(n:number)=>Math.max(0,Math.min(1,n));
const range=(f:number,a:number,b:number)=>clamp((f-a)/Math.max(1,b-a));
const ease=(n:number)=>1-Math.pow(1-clamp(n),3);
export const voxAudioCache=new Map<string,MediaUtilsAudioData>();
type SceneProps={p:VoxAnimationProps;id:string;f:number;d:number;w:number;h:number;images:string[];audio?:string;payload:VoxAnimationPayload};
const lines=(p:VoxAnimationProps)=>p.items.length?p.items:[{label:p.title,detail:p.subtitle,value:0,date:'',lat:0,lng:0}];
const card:CSSProperties={background:'#fffdf8',color:'#242820',padding:'6%',border:'3px solid #ffffff',boxShadow:'0 14px 30px #00000020',overflowWrap:'anywhere'};
const textStyle:CSSProperties={margin:0,lineHeight:1.2,overflowWrap:'anywhere',whiteSpace:'pre-wrap'};
function Reveal({children,f,at=0,style={}}:{children:React.ReactNode;f:number;at?:number;style?:CSSProperties}){const a=ease(range(f,at,at+18));return <div style={{opacity:a,transform:`translateY(${(1-a)*45}px)`,...style}}>{children}</div>;}
function Marked({text,highlight,progress,accent}:{text:string;highlight:string;progress:number;accent:string}){
  const words=highlight.split(/[，,\n]/).map(x=>x.trim()).filter(Boolean);if(!words.length)return <>{text}</>;
  const parts=text.split(new RegExp(`(${words.map(w=>w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')})`,'g'));
  return <>{parts.map((part,i)=>words.includes(part)?<span key={i} style={{backgroundImage:`linear-gradient(${accent}70,${accent}70)`,backgroundRepeat:'no-repeat',backgroundPosition:'left 88%',backgroundSize:`${clamp(progress*words.length-words.indexOf(part))*100}% 42%`}}>{part}</span>:part)}</>;
}
function Paper(s:SceneProps){const {p,id,f,d,images,w,h}=s;const items=lines(p);const portrait=h>w;
  if(id==='paper-title')return <div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',gap:28}}>{p.title.split(/(?<=[，。！？：\s])/u).filter(Boolean).map((t,i)=><Reveal f={f} at={i*12} key={i} style={{fontSize:portrait?88:100,fontWeight:900,transform:`scale(${1+.18*(1-ease(range(f,i*12,i*12+15)))})`}}>{t}</Reveal>)}<Reveal f={f} at={25} style={{fontSize:34}}>{p.subtitle}</Reveal></div>;
  if(id==='paper-actors')return <AbsoluteFill><Img src={images[0]} style={{width:'100%',height:'100%',objectFit:'cover'}}/>{images.slice(1).map((src,i)=>{const a=spring({frame:f-i*14-8,fps:s.payload.fps,config:{damping:16}});return <Img key={src+i} src={src} style={{position:'absolute',bottom:'5%',left:`${10+i*22}%`,width:'65%',height:'85%',objectFit:'contain',filter:'drop-shadow(4px 0 white) drop-shadow(-4px 0 white) drop-shadow(0 15px 12px #0005)',transform:`translateX(${(1-a)*(i%2?100:-150)}px) rotate(${(1-a)*-8}deg) scale(${.9+a*.1})`,opacity:clamp(a)}}/>;})}<div style={{position:'absolute',top:'6%',left:'6%',right:'6%',fontSize:portrait?72:80,fontWeight:900,color:p.foreground,background:`${p.background}dc`,padding:20}}>{p.title}</div></AbsoluteFill>;
  return <div style={{display:'grid',gridTemplateColumns:portrait?'1fr 1fr':`repeat(${Math.min(4,Math.max(1,images.length||items.length))},1fr)`,gap:30,alignItems:'center',height:'100%',perspective:1200}}>{(images.length?images:items.map(()=>undefined)).slice(0,8).map((src,i)=>{const a=ease(range(f,8+i*14,35+i*14));return <div key={i} style={{...card,padding:18,opacity:a,transform:id==='paper-popup'?`rotateX(${(1-a)*-85}deg) translateY(${(1-a)*80}px)`:`translateY(${(1-a)*120}px) rotate(${i%2?5:-5}deg)`,transformOrigin:'50% 100%'}}>{src?<Img src={src} style={{width:'100%',height:portrait?260:230,objectFit:'contain'}}/>:<div style={{fontSize:40,minHeight:120}}>{items[i]?.label}</div>}<p style={{...textStyle,fontSize:25,marginTop:18}}>{items[i]?.detail||items[i]?.label||p.subtitle}</p></div>;})}</div>;
}
function Evidence(s:SceneProps){const {p,id,f,d,images}=s;
  if(id==='evidence-chat'){
    const items=lines(p),active=Math.min(items.length-1,Math.floor(f/Math.max(1,d/items.length)));
    return <div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',gap:18}}>{items.slice(Math.max(0,active-2),active+1).map((x,j)=>{const i=Math.max(0,active-2)+j;return <Reveal key={i} f={f} at={i*d/items.length} style={{alignSelf:i%2?'flex-end':'flex-start',maxWidth:'85%',padding:'18px 24px',borderRadius:18,background:i%2?p.accent:p.foreground,color:p.background,fontSize:27}}><small style={{fontSize:19,opacity:.8}}>{x.label}</small><div>{x.detail}</div></Reveal>})}</div>;
  }
  if(id==='evidence-focus'){const q=p.focus,a=ease(range(f,d*.15,d*.6));const zoom=1+(Math.min(3,1/Math.max(q.width,q.height))-1)*a;return <div style={{height:'100%',position:'relative',overflow:'hidden'}}><Img src={images[0]} style={{width:'100%',height:'100%',objectFit:'contain',transformOrigin:`${(q.x+q.width/2)*100}% ${(q.y+q.height/2)*100}%`,transform:`scale(${zoom})`}}/><div style={{position:'absolute',left:`${q.x*100}%`,top:`${q.y*100}%`,width:`${q.width*100}%`,height:`${q.height*100}%`,border:`5px solid ${p.accent}`,opacity:1-a}}/><Reveal f={f} at={Math.round(d*.6)} style={{position:'absolute',bottom:10,left:10,right:10,...card,fontSize:30}}>{p.subtitle||p.title}</Reveal></div>;}
  if(id==='evidence-stack')return <div style={{position:'relative',height:'100%'}}>{lines(p).slice(0,10).map((x,i)=>{const active=Math.min(lines(p).length-1,Math.floor(f/Math.max(1,d/lines(p).length)));return <Reveal f={f} at={i*d/lines(p).length} key={i} style={{...card,position:'absolute',inset:`${i*8}px ${i*3}px auto`,fontSize:40,transform:`rotate(${i%2?2:-2}deg)`,opacity:i<=active?1:0}}>{images[i]?<Img src={images[i]} style={{height:180,width:'100%',objectFit:'contain'}}/>:null}<h3>{x.label}</h3><p style={{fontSize:30}}>{x.detail}</p><small>{p.source}</small></Reveal>;})}</div>;
  return <Reveal f={f} style={{...card,height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',gap:32,borderTop:`12px solid ${p.accent}`}}><div style={{fontSize:22,color:p.accent}}>{id==='evidence-quote'?p.author:p.source}</div><p style={{...textStyle,fontSize:p.subtitle.length>150?36:52,fontWeight:id==='evidence-headline'?800:500}}><Marked text={p.subtitle||p.title} highlight={p.highlight} progress={range(f,20,d*.75)} accent={p.accent}/></p><Reveal f={f} at={30} style={{fontSize:22,opacity:.7}}>{id==='evidence-quote'?p.source:p.author}</Reveal></Reveal>;
}
function Timeline(s:SceneProps){const {p,id,f,d,w,h}=s;const items=lines(p),portrait=h>w;
  if(id==='time-year-counter'){const first=Number(p.items[0]?.date||p.items[0]?.value||0),last=Number(p.items.at(-1)?.date||p.items.at(-1)?.value||first);return <div style={{textAlign:'center',height:'100%',display:'flex',flexDirection:'column',justifyContent:'center'}}><div style={{fontSize:160,fontWeight:900,color:p.accent}}>{Math.round(first+(last-first)*ease(range(f,8,d*.8)))}</div><p style={{fontSize:42}}>{p.subtitle}</p></div>;}
  if(id==='time-chapters')return <div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',gap:35}}><Reveal f={f} style={{fontSize:150,color:p.accent,fontWeight:900}}>{p.items[0]?.date||p.items[0]?.label||'01'}</Reveal><Reveal f={f} at={16} style={{fontSize:65,fontWeight:800}}>{p.title}</Reveal><Reveal f={f} at={25} style={{fontSize:32}}>{p.subtitle}</Reveal></div>;
  if(id==='time-travel'){const pos=ease(range(f,12,d*.85))*(items.length-1);return <div style={{height:'100%',position:'relative',overflow:'hidden'}}><div style={{position:'absolute',top:'50%',display:'flex',gap:70,transform:`translate(${w*.12-pos*410}px,-50%)`}}>{items.map((x,i)=><div key={i} style={{...card,width:340,flexShrink:0,borderTop:`8px solid ${p.accent}`,transform:`scale(${1-.13*Math.min(1,Math.abs(pos-i))})`}}><strong style={{fontSize:50,color:p.accent}}>{x.date}</strong><h3 style={{fontSize:38}}>{x.label}</h3><p style={{fontSize:26}}>{x.detail}</p></div>)}</div></div>;}
  return <div style={{display:'grid',gap:Math.max(12,55-items.length*4),height:'100%',alignContent:'center'}}>{items.slice(0,10).map((x,i)=><Reveal key={i} f={f} at={i*d*.65/items.length} style={{display:'grid',gridTemplateColumns:portrait?'130px 1fr':'180px 1fr',gap:28,borderLeft:`5px solid ${p.accent}`,paddingLeft:24}}><strong style={{fontSize:portrait?32:40,color:p.accent}}>{x.date||String(i+1).padStart(2,'0')}</strong><div><b style={{fontSize:32}}>{x.label}</b><p style={{fontSize:24,margin:'8px 0'}}>{x.detail}</p></div></Reveal>)}</div>;
}
function Compare(s:SceneProps){const {p,id,f,d,images,h,w}=s,items=lines(p),portrait=h>w;
  if(id==='compare-slider')return <div style={{position:'relative',height:'100%',overflow:'hidden'}}><Img src={images[0]} style={{width:'100%',height:'100%',objectFit:'contain'}}/><Img src={images[1]} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'contain',clipPath:`inset(0 ${100-ease(range(f,15,d*.85))*100}% 0 0)`}}/><div style={{position:'absolute',top:0,bottom:0,left:`${ease(range(f,15,d*.85))*100}%`,width:5,background:p.accent}}/></div>;
  if(id==='compare-values')return <Data {...s} id="data-bars"/>;
  return <div style={{display:'grid',height:'100%',gridTemplateColumns:portrait?'1fr':'1fr 1fr',gap:30}}>{items.slice(0,2).map((x,i)=><Reveal key={i} f={f} at={id==='compare-claims'?i*d*.45:i*16} style={{...card,display:'flex',flexDirection:'column',justifyContent:'center',gap:20,borderTop:`8px solid ${i?p.foreground:p.accent}`}}>{images[i]?<Img src={images[i]} style={{width:'100%',height:portrait?220:250,objectFit:'contain'}}/>:null}<b style={{fontSize:45,color:i?p.foreground:p.accent}}>{x.label}</b><p style={{...textStyle,fontSize:30}}>{x.detail}</p></Reveal>)}</div>;
}
function Data(s:SceneProps){const {p,id,f,d}=s,items=lines(p);const a=ease(range(f,10,d*.72)),max=Math.max(1,...items.map(x=>Math.abs(x.value))),colors=[p.accent,p.foreground,'#6b8269','#b68c45','#7a7599','#537f94'];
  if(id==='data-ranking'&&new Set(items.map(x=>x.label)).size<items.length){
    const dates=[...new Set(items.map(x=>x.date))],names=[...new Set(items.map(x=>x.label))];
    const pos=range(f,12,d*.85)*(dates.length-1),index=Math.floor(pos),mix=pos-index;
    const values=names.map(label=>{const start=items.find(x=>x.label===label&&x.date===dates[index])?.value??0,end=items.find(x=>x.label===label&&x.date===dates[Math.min(index+1,dates.length-1)])?.value??start;return {label,value:start+(end-start)*mix};}).sort((a,b)=>b.value-a.value);
    const largest=Math.max(1,...values.map(x=>Math.abs(x.value)));
    return <div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',gap:22}}><b style={{fontSize:40,color:p.accent}}>{dates[index]}</b>{values.map((x,i)=><div key={x.label} style={{display:'grid',gridTemplateColumns:'200px 1fr 110px',gap:20,alignItems:'center',fontSize:28}}><span>{i+1}. {x.label}</span><div style={{height:42,width:`${Math.abs(x.value)/largest*100}%`,background:colors[names.indexOf(x.label)%colors.length]}}/><b>{x.value.toFixed(0)}{p.unit}</b></div>)}</div>;
  }
  if(id==='data-counter')return <div style={{height:'100%',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}><strong style={{fontSize:Math.max(60,Math.min(180,950/(String(items[0].value).length+2))),color:p.accent,fontVariantNumeric:'tabular-nums'}}>{(items[0].value*a).toLocaleString('zh-CN',{maximumFractionDigits:Number.isInteger(items[0].value)?0:2})}<small style={{fontSize:40}}>{p.unit}</small></strong><p style={{fontSize:40}}>{items[0].label}</p></div>;
  if(id==='data-line'){const min=Math.min(0,...items.map(x=>x.value)),span=Math.max(1,max-min);const points=items.map((x,i)=>[60+i*780/Math.max(1,items.length-1),400-(x.value-min)/span*340]);return <svg viewBox="0 0 900 510" style={{width:'100%',height:'100%'}}><path d="M60 45V400H850" fill="none" stroke={p.foreground} strokeWidth="2"/><path d={points.map(([x,y],i)=>`${i?'L':'M'}${x},${y}`).join(' ')} fill="none" stroke={p.accent} strokeWidth="7" pathLength="1" strokeDasharray="1" strokeDashoffset={1-a}/>{points.map(([x,y],i)=><g key={i} opacity={a>=i/Math.max(1,points.length-1)?1:0}><circle cx={x} cy={y} r="7" fill={p.accent}/><text x={x} y={y-20} textAnchor="middle" fontSize="22" fill={p.foreground}>{items[i].value}{p.unit}</text><text x={x} y="445" textAnchor="middle" fontSize="20" fill={p.foreground}>{items[i].date||items[i].label}</text></g>)}</svg>;}
  if(id==='data-share'){const total=items.reduce((n,x)=>n+Math.max(0,x.value),0)||1;let offset=0;return <div style={{display:'flex',flexWrap:'wrap',height:'100%',alignItems:'center',justifyContent:'center',gap:35}}><svg viewBox="0 0 400 400" style={{width:'52%',minWidth:280}}>{items.map((x,i)=>{const portion=Math.max(0,x.value)/total,start=offset;offset+=portion;return <circle key={i} cx="200" cy="200" r="140" fill="none" stroke={colors[i%colors.length]} strokeWidth="65" pathLength="1" strokeDasharray={`${portion*a} ${1-portion*a}`} strokeDashoffset={-start} transform="rotate(-90 200 200)"/>})}</svg><div style={{fontSize:28}}>{items.map((x,i)=><p key={i} style={{borderLeft:`8px solid ${colors[i%colors.length]}`,paddingLeft:18}}>{x.label} · {(x.value/total*100).toFixed(1)}%</p>)}</div></div>;}
  const ordered=id==='data-ranking'?[...items].sort((a,b)=>b.value-a.value):items;return <div style={{display:'grid',alignContent:'center',gap:Math.max(15,45-items.length*2),height:'100%'}}>{ordered.slice(0,12).map((x,i)=>{const progress=ease(range(f,8+i*4,d*.7+i*4));return <div key={i} style={{display:'grid',gridTemplateColumns:'180px 1fr 140px',alignItems:'center',gap:20,fontSize:28}}><div>{id==='data-ranking'?`${i+1}. `:''}{x.label}</div><div style={{height:44,background:`${p.foreground}10`,borderRadius:3,overflow:'hidden'}}><div style={{height:'100%',background:colors[i%colors.length],width:`${Math.abs(x.value)/max*progress*100}%`}}/></div><b style={{fontSize:26}}>{(x.value*progress).toLocaleString('zh-CN',{maximumFractionDigits:1})}{p.unit}</b></div>;})}</div>;
}
function MapScene(s:SceneProps){const {p,id,f,d}=s;const items=p.items;let polygons:number[][][]=worldMap;
  if(p.geoJson.trim()){try{const g=JSON.parse(p.geoJson),features=g.type==='FeatureCollection'?g.features:[g.type==='Feature'?g:{geometry:g}];polygons=features.flatMap((x:any)=>x.geometry.type==='Polygon'?[x.geometry.coordinates[0]]:x.geometry.type==='MultiPolygon'?x.geometry.coordinates.map((a:any)=>a[0]):[]);}catch{/* Validation reports malformed input before application. */}}
  const project=(lng:number,lat:number)=>[(lng+180)*1000/360,(90-lat)*500/180];
  let bounds=[0,0,1000,500];if(id==='map-region'&&polygons.length){const pts=polygons.flat().map(([x,y])=>project(x,y));const xs=pts.map(x=>x[0]),ys=pts.map(x=>x[1]);const x=Math.min(...xs),y=Math.min(...ys);bounds=[x-15,y-15,Math.max(50,Math.max(...xs)-x+30),Math.max(50,Math.max(...ys)-y+30)];}
  const progress=range(f,12,d*.85),points=items.map(x=>project(x.lng,x.lat));
  if(id!=='map-region'&&points.length>1){
    const xs=points.map(x=>x[0]),ys=points.map(x=>x[1]),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2;
    const bw=Math.max(85,(Math.max(...xs)-Math.min(...xs))*1.6),bh=Math.max(60,(Math.max(...ys)-Math.min(...ys))*2);
    const zoom=ease(range(f,0,d*.35)),target=[cx-bw/2,cy-bh/2,bw,bh];bounds=bounds.map((x,i)=>x+(target[i]-x)*zoom);
  }
  const mapScale=Math.max(bounds[2]/880,bounds[3]/260);
  return <div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center'}}><svg viewBox={bounds.join(' ')} style={{width:'100%',height:'80%',overflow:'hidden'}}>{polygons.map((poly,i)=><path key={i} d={poly.map(([x,y],j)=>`${j?'L':'M'}${project(x,y).join(',')}`).join(' ')+'Z'} fill={id==='map-region'?`${p.accent}90`:`${p.foreground}16`} stroke={p.background} strokeWidth={mapScale*.7}/>) }{points.slice(1).map(([x,y],i)=>{const [sx,sy]=points[i];const bend=Math.min(80,Math.hypot(x-sx,y-sy)*.25);const a=clamp(progress*(points.length-1)-i);return <path key={i} d={`M${sx},${sy} Q${(sx+x)/2},${(sy+y)/2-bend} ${x},${y}`} pathLength="1" strokeDasharray="1" strokeDashoffset={1-a} fill="none" stroke={p.accent} strokeWidth={4*mapScale}/>})}{points.map(([x,y],i)=><g key={i} opacity={progress>=i/Math.max(1,points.length-1)?1:0}><circle cx={x} cy={y} r={5*mapScale} fill={p.accent}/><text x={x} y={y-13*mapScale} fontSize={22*mapScale} textAnchor="middle" fill={p.foreground} stroke={p.background} strokeWidth={3*mapScale} paintOrder="stroke">{items[i].label}</text></g>)}</svg><div style={{fontSize:30,textAlign:'center',marginTop:25}}>{items[Math.min(items.length-1,Math.floor(progress*items.length))]?.[id==='map-history'?'date':'detail']||p.subtitle}</div><div style={{fontSize:15,textAlign:'right',opacity:.6}}>底图：Natural Earth · {p.source}</div></div>;
}
function Flow(s:SceneProps){const {p,id,f,d}=s,items=lines(p).slice(0,10);const progress=range(f,10,d*.8);
  if(id==='flow-rings')return <div style={{height:'100%',display:'flex',alignItems:'center',gap:30}}><svg viewBox="0 0 500 500" style={{width:'60%'}}>{items.map((x,i)=><circle key={i} cx="250" cy="250" r={55+i*165/Math.max(1,items.length-1)} fill="none" stroke={i%2?p.foreground:p.accent} strokeWidth="13" pathLength="1" strokeDasharray={`${clamp(progress*items.length-i)} 1`} transform="rotate(-90 250 250)"/> )}</svg><div style={{fontSize:28}}>{items.map((x,i)=><Reveal f={f} at={i*d*.6/items.length} key={i}><p><b>{x.label}</b><br/>{x.detail}</p></Reveal>)}</div></div>;
  if(id==='flow-converge')return <svg viewBox="0 0 900 700" style={{width:'100%',height:'100%'}}>{items.map((x,i)=>{const y=70+i*550/Math.max(1,items.length-1),a=clamp(progress*2-i/items.length);return <g key={i}><path d={`M250 ${y} C500 ${y} 480 350 650 350`} pathLength="1" fill="none" stroke={p.accent} strokeWidth="4" strokeDasharray="1" strokeDashoffset={1-a}/><rect x="20" y={y-35} width="235" height="70" rx="8" fill={p.foreground}/><text x="137" y={y+8} fill={p.background} fontSize="25" textAnchor="middle">{x.label}</text></g>})}<rect x="650" y="285" width="230" height="130" rx="10" fill={p.accent}/><text x="765" y="358" fontSize="28" textAnchor="middle" fill="white">{p.subtitle||p.title}</text></svg>;
  return <div style={{display:'grid',alignContent:'center',height:'100%',gap:22}}>{items.map((x,i)=><Reveal f={f} at={i*d*.65/items.length} key={i} style={{position:'relative',padding:'18px 25px',borderLeft:`6px solid ${p.accent}`,background:`${p.foreground}08`,display:'grid',gridTemplateColumns:'65px 1fr',gap:20}}><strong style={{fontSize:38,color:p.accent}}>{i+1}</strong><div><b style={{fontSize:32}}>{x.label}</b><p style={{fontSize:24,margin:'8px 0'}}>{x.detail}</p></div>{i<items.length-1?<div style={{position:'absolute',height:22,width:4,background:p.accent,left:54,top:'100%'}}>{id==='flow-energy'?<div style={{width:10,height:10,borderRadius:'50%',background:p.foreground,transform:`translate(-3px,${(f%24)/24*17}px)`}}/>:null}</div>:null}</Reveal>)}</div>;
}
function Book(s:SceneProps){const {p,id,f,d,images,w,h}=s;const portrait=h>w;
  if(id==='book-excerpt')return <Evidence {...s} id="evidence-quote"/>;
  if(id==='book-directory')return <Timeline {...s} id="time-milestones"/>;
  if(id==='book-reading-list')return <Gallery {...s} id="gallery-carousel"/>;
  if(id==='book-3d'){const pageCount=Math.max(1,images.length-1);const t=range(f,10,d*.9)*pageCount;return <div style={{height:'100%',display:'flex',alignItems:'center',justifyContent:'center',perspective:1800}}><div style={{width:portrait?'65%':'43%',height:'85%',position:'relative',transform:'rotateY(-15deg) rotateX(6deg)',transformStyle:'preserve-3d'}}><div style={{position:'absolute',inset:0,background:'#e5dfcf',transform:'translateZ(-16px)',boxShadow:'18px 25px 28px #0005',border:'10px solid #e6dfca'}}/>{[...Array(pageCount)].map((_,j)=>{const i=pageCount-1-j,a=clamp(t-i);return <div key={i} style={{position:'absolute',inset:0,background:'#fffaf0',transformOrigin:'left center',transform:`translateZ(${i+1}px) rotateY(${-a*165}deg)`,transformStyle:'preserve-3d',boxShadow:'2px 0 6px #0004',borderLeft:`10px solid ${p.accent}`}}><Img src={images[i+1]||images[0]} style={{width:'100%',height:'100%',objectFit:'contain',backfaceVisibility:'hidden'}}/></div>})}<div style={{position:'absolute',inset:0,transformOrigin:'left center',transform:`translateZ(20px) rotateY(${-ease(range(f,0,d*.3))*170}deg)`,backfaceVisibility:'hidden',boxShadow:'6px 0 12px #0005'}}><Img src={images[0]} style={{width:'100%',height:'100%',objectFit:'contain',background:p.background}}/></div></div></div>;}
  return <div style={{height:'100%',display:'grid',gridTemplateColumns:portrait?'1fr':'40% 1fr',gap:35,alignItems:'center'}}><Reveal f={f} style={{height:portrait?400:'85%',transform:`rotateY(${-15+ease(range(f,0,35))*15}deg)`,perspective:1000}}>{images[0]?<Img src={images[0]} style={{width:'100%',height:'100%',objectFit:'contain',filter:'drop-shadow(14px 16px 12px #0003)'}}/>:<div style={{...card,height:'100%',borderLeft:`14px solid ${p.accent}`,fontSize:42,display:'flex',flexDirection:'column',justifyContent:'center'}}>{p.title}<small style={{fontSize:25,marginTop:20}}>{p.author}</small></div>}</Reveal><div>{id==='book-identity'?<Reveal f={f} at={15} style={{fontSize:48,fontWeight:800}}>{p.title}</Reveal>:null}<p style={{fontSize:26,color:p.accent}}>{p.author}</p>{id==='book-takeaways'?lines(p).slice(0,6).map((x,i)=><Reveal key={i} f={f} at={25+i*d*.5/Math.max(1,p.items.length)} style={{marginTop:25,fontSize:30}}><b>{i+1}. {x.label}</b><p style={{fontSize:24}}>{x.detail}</p></Reveal>):<Reveal f={f} at={25} style={{fontSize:32,lineHeight:1.7,whiteSpace:'pre-wrap'}}>{p.subtitle}</Reveal>}</div></div>;
}
function Gallery(s:SceneProps){const {p,id,f,d,images}=s,items=lines(p);if(id==='gallery-grid')return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24,height:'100%',alignContent:'center'}}>{images.slice(0,8).map((src,i)=><Reveal key={i} f={f} at={i*10}><Img src={src} style={{width:'100%',height:190,objectFit:'contain'}}/><p style={{fontSize:23}}>{items[i]?.label}</p></Reveal>)}</div>;
  const n=Math.max(1,images.length),pos=range(f,10,d*.85)*(n-1);return <div style={{position:'relative',height:'100%',perspective:1200,overflow:'hidden'}}>{images.map((src,i)=>{const distance=i-pos;return <div key={i} style={{position:'absolute',width:'65%',height:'85%',left:'17.5%',top:'5%',opacity:clamp(1-Math.abs(distance)*.35),transform:`translateX(${distance*500}px) translateZ(${-Math.abs(distance)*200}px) rotateY(${id==='gallery-space'?distance*-35:0}deg)`}}><Img src={src} style={{width:'100%',height:'85%',objectFit:'contain',filter:'drop-shadow(0 15px 15px #0002)'}}/><p style={{fontSize:30,textAlign:'center'}}>{items[i]?.label}<small style={{display:'block',fontSize:22}}>{items[i]?.detail}</small></p></div>})}</div>;
}
function AudioScene(s:SceneProps){const {p,id,f,d,audio,payload,images}=s,cache=audio?voxAudioCache.get(audio):undefined;
  if(id==='audio-captions'||id==='audio-lyrics')return null;
  const ms=f/payload.fps*1000,clip=payload.audioClips?.find(x=>x.assetVersionId===p.audioAssetId&&ms>=x.startMs&&ms<x.startMs+x.durationMs);
  const audioFrame=clip?(ms-clip.startMs+(clip.sourceStartMs??0))*payload.fps/1000:f;
  const audible=payload.audioClips===undefined||Boolean(clip&&!clip.muted);
  const samples=cache&&audible?(id==='audio-podcast'?Array.from({length:64},(_,i)=>{
    const wave=cache.channelWaveforms[0],center=Math.floor(audioFrame/payload.fps*cache.sampleRate),start=center+Math.floor((i-32)*cache.sampleRate/64);
    let peak=0;for(let j=0;j<Math.floor(cache.sampleRate/64);j+=8)peak=Math.max(peak,Math.abs(wave[start+j]??0));return peak*.15;
  }):visualizeAudio({audioData:cache,frame:audioFrame,fps:payload.fps,numberOfSamples:64,smoothing:true})):[];
  return <div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',alignItems:'center',gap:40}}>{images[0]?<Img src={images[0]} style={{width:250,height:250,objectFit:'contain',borderRadius:id==='audio-podcast'?'50%':0}}/>:null}<b style={{fontSize:48,textAlign:'center'}}>{p.title}</b><svg viewBox="0 0 900 260" style={{width:'100%'}}>{samples.map((v,i)=><rect key={i} x={i*14} y={130-Math.min(120,v*800)} width="9" height={Math.max(2,Math.min(240,v*1600))} rx="4" fill={i%3?p.accent:p.foreground}/>)}</svg><p style={{fontSize:28}}>{p.subtitle}</p></div>;
}
function Transition(s:SceneProps){const {p,id,f,d,images}=s,a=ease(range(f,d*.2,d*.8));const layer=(i:number)=><div style={{width:'100%',height:'100%',display:'flex',alignItems:'center',justifyContent:'center',fontSize:65,fontWeight:800,color:i?p.background:p.foreground,background:i?p.foreground:p.background}}>{images[i]?<Img src={images[i]} style={{width:'100%',height:'100%',objectFit:'contain'}}/>:(i?p.subtitle:p.title)}</div>;
 return <div style={{height:'100%',position:'relative',perspective:1200,overflow:'hidden'}}>{layer(1)}<div style={{position:'absolute',inset:0,transformOrigin:id==='transition-page'?'left center':`${p.focus.x*100}% ${p.focus.y*100}%`,transform:id==='transition-page'?`rotateY(${-a*100}deg)`:id==='transition-zoom'?`scale(${1+a*5})`:'none',backfaceVisibility:'hidden',opacity:id==='transition-zoom'?1-range(a,.65,1):1,clipPath:id==='transition-ink'?`circle(${(1-a)*150}% at 50% 50%)`:undefined}}>{layer(0)}</div></div>;
}
function noHeadingFor(id:string){return ['text-opening','text-keywords','label-lower-third','paper-title','time-chapters','book-identity','audio-captions','audio-lyrics','audio-podcast','audio-spectrum'].includes(id);}
export function VoxComposition(payload:VoxAnimationPayload){const frame=useCurrentFrame(),config=useVideoConfig();const {animation}=payload,p=animation.template.props,id=animation.template.id;const w=1000,h=config.height/config.width*w;const images=p.assetIds.flatMap(id=>payload.assets.find(a=>a.id===id&&a.kind==='image')?.url??[]),audio=payload.assets.find(a=>a.id===p.audioAssetId)?.url;
  if(shotcraftRecipe(id))return <ShotcraftComposition payload={payload} frame={frame} durationInFrames={config.durationInFrames}/>;
  const stageTop=noHeadingFor(id)?50:Math.max(105,Math.min(220,Math.ceil(p.title.length/17)*62));
  const stageHeight=h-stageTop-Math.max(110,h*(p.source?.24:.19)),portrait=h>w;
  const count=Math.max(1,p.items.length);
  const minimumHeight=id==='audio-podcast'||id==='audio-spectrum'?720:id==='gallery-grid'?Math.ceil(Math.min(8,images.length)/2)*280:
    id==='book-takeaways'?(portrait?1000:Math.min(6,count)*140+150):id==='book-identity'?430:
    id==='compare-split'||id==='compare-claims'?(portrait?1040:560):id==='data-share'?470:
    ['flow-steps','flow-causal','flow-energy'].includes(id)?Math.min(10,count)*142:
    ['time-milestones','book-directory'].includes(id)?Math.min(10,count)*115:
    id==='time-travel'?480:id==='time-year-counter'?330:id==='evidence-stack'?470:
    ['evidence-quote','evidence-headline','book-excerpt'].includes(id)?Math.max(350,Math.ceil((p.subtitle||p.title).length/16)*65+160):
    id==='paper-popup'||id==='paper-polaroids'?(portrait?Math.ceil(images.length/2)*410:380):0;
  const logicalHeight=Math.max(stageHeight,minimumHeight),stageScale=Math.min(1,stageHeight/logicalHeight);
  const s:SceneProps={p,id,f:frame,d:config.durationInFrames,w,h,images,audio,payload};const section=id.split('-')[0];const full=['paper-actors'].includes(id);const noHeading=['text-opening','text-keywords','label-lower-third','paper-title','time-chapters','book-identity','audio-captions','audio-lyrics','audio-podcast','audio-spectrum'].includes(id);
  let content:React.ReactNode;
  if(section==='paper')content=<Paper {...s}/>;else if(section==='evidence')content=<Evidence {...s}/>;else if(section==='time')content=<Timeline {...s}/>;else if(section==='compare')content=<Compare {...s}/>;else if(section==='data')content=<Data {...s}/>;else if(section==='map')content=<MapScene {...s}/>;else if(section==='flow')content=<Flow {...s}/>;else if(section==='book')content=<Book {...s}/>;else if(section==='gallery')content=<Gallery {...s}/>;else if(section==='audio')content=<AudioScene {...s}/>;else if(section==='transition')content=<Transition {...s}/>;else if(section==='label')content=<Reveal f={frame} at={8} style={{position:'absolute',left:60,right:60,bottom:'18%',borderLeft:`10px solid ${p.accent}`,background:`${p.background}ef`,padding:35}}><b style={{fontSize:55}}>{p.title}</b><p style={{fontSize:30}}>{p.subtitle}</p></Reveal>;else content=<div style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center',gap:35}}><Reveal f={frame} style={{fontSize:p.title.length>45?65:90,fontWeight:900}}><Marked text={p.title} highlight={p.highlight} progress={range(frame,10,config.durationInFrames*.75)} accent={p.accent}/></Reveal><Reveal f={frame} at={20} style={{fontSize:36,lineHeight:1.6}}>{p.subtitle}</Reveal></div>;
  return <AbsoluteFill style={{background:p.background,color:p.foreground,fontFamily:'Microsoft YaHei, Noto Sans CJK SC, sans-serif'}}><div style={{position:'absolute',width:w,height:h,transform:`scale(${config.width/w})`,transformOrigin:'top left',overflow:'hidden'}}>{!noHeading&&!full?<div style={{position:'absolute',left:60,right:60,top:40,fontSize:h>w?57:50,fontWeight:850,lineHeight:1.25,overflowWrap:'anywhere'}}>{p.title}</div>:null}<div style={{position:'absolute',inset:full?'0':`${stageTop}px 60px ${Math.max(110,h*(p.source?.24:.19))}px`,overflow:'hidden'}}><div style={full?{height:'100%'}:{position:'absolute',width:880,height:logicalHeight,left:'50%',top:'50%',transform:`translate(-50%,-50%) scale(${stageScale})`}}>{content}</div></div>{p.source&&!['evidence','map'].includes(section)?<div style={{position:'absolute',left:60,bottom:Math.max(88,h*.18),fontSize:18,opacity:.65}}>{p.source}</div>:null}</div></AbsoluteFill>;
}
