import { webDarkTheme, webLightTheme, type Theme } from '@fluentui/react-components';

export const storyDreamDarkTheme: Theme = {
  ...webDarkTheme,
  colorBrandForeground1: '#ff755f',
  colorBrandForeground2: '#f2614b',
  colorBrandBackground: '#f2614b',
  colorBrandBackgroundHover: '#ff755f',
  colorBrandBackgroundPressed: '#d94f3b',
  colorBrandBackgroundSelected: '#f2614b',
  colorBrandStroke1: '#f2614b',
  colorBrandStroke2: '#ff755f',
  colorCompoundBrandForeground1: '#ff755f',
  colorCompoundBrandForeground1Hover: '#ff8d7b',
  colorCompoundBrandForeground1Pressed: '#f2614b',
  colorCompoundBrandBackground: '#f2614b',
  colorCompoundBrandBackgroundHover: '#ff755f',
  colorCompoundBrandBackgroundPressed: '#d94f3b',
  colorCompoundBrandStroke: '#f2614b',
  colorCompoundBrandStrokeHover: '#ff755f',
  colorCompoundBrandStrokePressed: '#d94f3b',
  colorNeutralForegroundOnBrand: '#101214',
  colorNeutralBackground1: '#101214',
  colorNeutralBackground2: '#15181b',
  colorNeutralBackground3: '#1b1f23',
  colorNeutralBackground4: '#24292e',
  colorNeutralForeground1: '#f4f6f8',
  colorNeutralForeground2: '#b1b8be',
  colorNeutralForeground3: '#8e979f',
  colorNeutralStroke1: '#343a40',
  colorNeutralStroke2: '#272c31',
  colorNeutralStrokeAccessible: '#727b83',
  colorStatusSuccessForeground1: '#65b883',
  colorStatusWarningForeground1: '#e0a34c',
  colorStatusDangerForeground1: '#ff6666',
  borderRadiusMedium: '6px',
  borderRadiusLarge: '8px',
  fontFamilyBase: 'var(--sd-font-ui)',
  fontFamilyNumeric: 'var(--sd-font-ui)',
};

export const storyDreamLightTheme: Theme = {
  ...webLightTheme,
  colorBrandForeground1: '#a93a2d',
  colorBrandForeground2: '#cf4938',
  colorBrandBackground: '#cf4938',
  colorBrandBackgroundHover: '#a93a2d',
  colorBrandBackgroundPressed: '#8d281d',
  colorBrandBackgroundSelected: '#cf4938',
  colorBrandStroke1: '#cf4938',
  colorBrandStroke2: '#a93a2d',
  colorCompoundBrandForeground1: '#a93a2d',
  colorCompoundBrandForeground1Hover: '#8d281d',
  colorCompoundBrandForeground1Pressed: '#77251c',
  colorCompoundBrandBackground: '#cf4938',
  colorCompoundBrandBackgroundHover: '#a93a2d',
  colorCompoundBrandBackgroundPressed: '#8d281d',
  colorCompoundBrandStroke: '#cf4938',
  colorCompoundBrandStrokeHover: '#a93a2d',
  colorCompoundBrandStrokePressed: '#8d281d',
  colorNeutralForegroundOnBrand: '#ffffff',
  colorNeutralBackground1: '#ffffff',
  colorNeutralBackground2: '#f6f7f8',
  colorNeutralBackground3: '#eaebed',
  colorNeutralBackground4: '#dedfe1',
  colorNeutralForeground1: '#202326',
  colorNeutralForeground2: '#5f6871',
  colorNeutralForeground3: '#7a8087',
  colorNeutralStroke1: '#e2e5e8',
  colorNeutralStroke2: '#e8e9eb',
  colorNeutralStrokeAccessible: '#747a81',
  colorStatusSuccessForeground1: '#18734a',
  colorStatusWarningForeground1: '#805300',
  colorStatusDangerForeground1: '#a92d36',
  borderRadiusMedium: '6px',
  borderRadiusLarge: '8px',
  fontFamilyBase: 'var(--sd-font-ui)',
  fontFamilyNumeric: 'var(--sd-font-ui)',
};

export function storyDreamTheme(theme: 'dark' | 'light'): Theme {
  return theme === 'light' ? storyDreamLightTheme : storyDreamDarkTheme;
}
