import type {
  AccountProfile,
  ActivationState,
  AppConfig,
  CreditTransaction,
  CustomStyle,
  MinimaxCloneVoice,
  PromptTemplate,
  UiPreferences,
} from './types';
import { DEFAULT_VOLCENGINE_TTS_V3_SPEAKER } from './volcengine-tts';

const updatedAt = '2026-05-26T00:00:00.000Z';

export const defaultConfig: AppConfig = {
  llm: {
    id: 'default-llm',
    name: '第三方',
    enabled: true,
    provider: 'custom',
    protocol: 'openai',
    apiKey: '',
    baseUrl: 'https://ai.input.im',
    model: 'gpt-5.5',
    proxyUrl: '',
    timeoutMs: 120000,
  },
  llmProfiles: [
    {
      id: 'default-llm',
      name: '第三方',
      enabled: true,
      provider: 'custom',
      protocol: 'openai',
      apiKey: '',
      baseUrl: 'https://ai.input.im',
      model: 'gpt-5.5',
      proxyUrl: '',
      timeoutMs: 120000,
    },
  ],
  activeLlmProfileId: 'default-llm',
  imageProvider: 'gpt_image',
  image: {
    baseUrl: '',
    apiKey: '',
    model: 'gpt-image-2',
    ratio: '9:16',
    concurrency: 3,
    resolution: '2K',
    proxyUrl: '',
  },
  gptImage: {
    baseUrl: '',
    apiKey: '',
    model: 'gpt-image-2',
    ratio: '9:16',
    concurrency: 3,
    resolution: '2K',
    proxyUrl: '',
  },
  jimeng: {
    sessionId: '',
    accessKeyId: '',
    secretAccessKey: '',
    reqKey: 'jimeng_t2i_v40',
    endpoint: 'https://visual.volcengineapi.com',
    region: 'cn-north-1',
    service: 'cv',
    pollIntervalMs: 2000,
    timeoutMs: 120000,
    model: 'jimeng-3.1',
    ratio: '9:16',
    resolution: '2K',
    concurrency: 3,
  },
  customImage: {
    displayName: '自定义图片接口',
    baseUrl: '',
    apiKey: '',
    model: 'gpt-image-2',
    ratio: '9:16',
    concurrency: 3,
    resolution: '2K',
    proxyUrl: '',
    asyncMode: false,
    ratioMappingJson: '{}',
  },
  imageProfiles: [
    {
      id: 'default-image',
      name: 'GPT Image',
      enabled: true,
      provider: 'gpt_image',
      gptImage: {
        baseUrl: '',
        apiKey: '',
        model: 'gpt-image-2',
        ratio: '9:16',
        concurrency: 3,
        resolution: '2K',
        proxyUrl: '',
      },
    },
  ],
  activeImageProfileId: 'default-image',
  tts: {
    provider: 'volcengine',
    appId: '',
    accessKey: '',
    speaker: DEFAULT_VOLCENGINE_TTS_V3_SPEAKER,
    volcengine: {
      apiKey: '',
      accessKeyId: '',
      secretAccessKey: '',
      appId: '',
      accessKey: '',
      speaker: DEFAULT_VOLCENGINE_TTS_V3_SPEAKER,
      cluster: 'volcano_tts',
      endpoint: 'https://openspeech.bytedance.com/api/v3/tts/unidirectional',
      resourceId: 'seed-tts-2.0',
    },
    minimax: {
      apiKey: '',
      model: 'speech-02-hd',
      voiceId: 'male-qn-qingse',
    },
  },
  ttsProfiles: [
    {
      id: 'default-tts',
      name: '火山引擎',
      enabled: true,
      provider: 'volcengine',
      appId: '',
      accessKey: '',
      speaker: DEFAULT_VOLCENGINE_TTS_V3_SPEAKER,
      volcengine: {
        apiKey: '',
        accessKeyId: '',
        secretAccessKey: '',
        appId: '',
        accessKey: '',
        speaker: DEFAULT_VOLCENGINE_TTS_V3_SPEAKER,
        cluster: 'volcano_tts',
        endpoint: 'https://openspeech.bytedance.com/api/v3/tts/unidirectional',
        resourceId: 'seed-tts-2.0',
      },
    },
  ],
  activeTtsProfileId: 'default-tts',
  jianying: {
    draftPath: 'G:/JianyingPro Drafts',
    bgmLibrary: [],
    defaultBgmId: '',
  },
  ima: {
    clientId: '',
    apiKey: '',
    kbId: '',
    kbName: '',
  },
  ui: {
    theme: 'dark',
  },
};

export const defaultPromptTemplates: PromptTemplate[] = [
  {
    id: 'system-character-story',
    name: '人物故事',
    type: 'task',
    description: '历史人物、名人传记、纪实质感与情感渲染。',
    content:
      '围绕 {{inputText}} 做人物故事短视频。保留可核验事实顺序，突出低谷、选择、转折和代价；口播要有开场反差、中段推进、结尾情绪落点。避免编造具体年份、人名和因果；如果资料不足，用克制表达说明不确定。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'character-story',
    defaultStyles: ['black-white'],
    characterPolicy: 'follow-template',
    step3SkeletonModules: ['跨年代', '防台词文字'],
    referenceKind: 'face',
    origin: 'system',
    usedCount: 0,
    marketTags: ['人物', '历史', '传记'],
  },
  {
    id: 'system-health-book',
    name: '健康图书',
    type: 'task',
    description: '健康养生、医学知识、书摘拆解。',
    content:
      '把 {{inputText}} 整理成健康科普/书摘短视频。先讲适用场景，再解释原理和边界；不做诊断、疗效承诺或替代就医建议。语言清楚、谨慎、可执行，重要风险必须提示。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'health-book',
    defaultStyles: ['magazine'],
    characterPolicy: 'force-skip',
    step3SkeletonModules: ['产品一致性'],
    referenceKind: 'none',
    origin: 'system',
  },
  {
    id: 'system-culture-science',
    name: '文化科普',
    type: 'task',
    description: '华夏文化、传统民俗、历史知识科普。',
    content:
      '把 {{inputText}} 拆成起因、过程、影响三段文化科普。先给一个具体场景或问题，再解释传统、人物、器物或制度背后的逻辑。语言有画面感但不神化、不猎奇、不夸大事实。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'culture-science',
    defaultStyles: ['ink'],
    characterPolicy: 'force-skip',
    step3SkeletonModules: ['防台词文字'],
    referenceKind: 'none',
    origin: 'system',
  },
  {
    id: 'system-picture-book',
    name: '绘本故事',
    type: 'task',
    description: '儿童绘本、睡前故事、轻叙事。',
    content:
      '把 {{inputText}} 改写成绘本/睡前故事。句子短、情绪温柔、画面明确，每段只推进一个动作或感受。避免惊吓、成人化冲突和复杂抽象概念，保留可被画出来的细节。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'picture-book',
    defaultStyles: ['watercolor'],
    characterPolicy: 'force-extract',
    step3SkeletonModules: ['跨年代'],
    referenceKind: 'face',
    origin: 'system',
  },
  {
    id: 'system-ecommerce',
    name: '电商带货',
    type: 'task',
    description: '产品种草、好物推荐、卖点脚本。',
    content:
      '把 {{inputText}} 改写成产品种草短视频。先呈现真实使用场景，再讲核心卖点、痛点解决、适合人群和购买理由。不要虚构功效、销量、认证和价格；{{extraRequirements}} 中的促销要求只在来源支持时保留。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'ecommerce',
    defaultStyles: ['photo-real'],
    characterPolicy: 'force-skip',
    step3SkeletonModules: ['产品一致性'],
    referenceKind: 'product',
    origin: 'system',
  },
  {
    id: 'system-mind-soup',
    name: '心灵鸡汤',
    type: 'task',
    description: '情感治愈、励志感悟、人生转折。',
    content:
      '把 {{inputText}} 写成情感治愈短视频。先给具体困境，再提炼一个能落到生活里的观点；少喊口号，多用动作、选择和细节承载情绪。结尾要有温和但有力量的落点。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'mind-soup',
    defaultStyles: ['modern-film'],
    characterPolicy: 'follow-template',
    step3SkeletonModules: ['防台词文字'],
    referenceKind: 'none',
    origin: 'system',
    marketTags: ['情感', '治愈', '励志'],
  },
  {
    id: 'system-folk-story',
    name: '民间故事',
    type: 'task',
    description: '虚构传说、因果寓言、乡土叙事。',
    content:
      '把 {{inputText}} 改写成民间故事短视频。叙事要有悬念、因果和反转，人物动机朴素清楚；画面可落在村镇、山林、集市、老屋等场景。虚构内容要保持故事内逻辑自洽。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'folk-story',
    defaultStyles: ['folk'],
    characterPolicy: 'force-extract',
    step3SkeletonModules: ['跨年代', '防台词文字'],
    referenceKind: 'none',
    origin: 'system',
    marketTags: ['民间', '传说', '寓言'],
  },
  {
    id: 'system-general-story',
    name: '通用故事',
    type: 'task',
    description: '通用写实叙事、口播故事、素材改写。',
    content:
      '把 {{inputText}} 改写成通用短视频故事。先抓住最有冲突的事实或情绪，再按“背景-变化-结果-余味”推进。语言口语化、节奏紧凑，避免空泛总结和无来源细节。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'general-story',
    defaultStyles: ['photo-real'],
    characterPolicy: 'follow-template',
    step3SkeletonModules: ['防台词文字'],
    referenceKind: 'none',
    origin: 'system',
    marketTags: ['通用', '故事', '改写'],
  },
  {
    id: 'system-food-v2',
    name: '美食探店V2',
    type: 'task',
    description: '城市街角小店、烟火气、探店口播。',
    content:
      '把 {{inputText}} 写成美食探店短视频。先给地点和烟火气氛围，再讲招牌菜、口感、价格/排队等可见信息；不要虚构店名、地址、评价和优惠。镜头要能拍到热气、手作、街边环境和真实食物细节。',
    isBuiltin: true,
    updatedAt,
    baseTrack: 'food-v2',
    defaultStyles: ['retro-film'],
    characterPolicy: 'force-skip',
    step3SkeletonModules: ['产品一致性', '防台词文字'],
    referenceKind: 'product',
    origin: 'system',
    marketTags: ['美食', '探店', '烟火气'],
  },
  {
    id: 'builtin-review',
    name: '预审整理',
    type: 'review',
    description: '清洗素材、去噪、压缩为适合短视频的事实文案。',
    content:
      '任务模板：{{taskTemplateContent}}\n\n素材：{{inputText}}\n\n资料来源：{{sourceContext}}\n\n请清洗素材、去除重复和明显广告噪音，保留事实顺序，输出适合后续改写的中文事实简稿。',
    isBuiltin: true,
    updatedAt,
    origin: 'system',
  },
  {
    id: 'builtin-rewrite',
    name: '短视频改写',
    type: 'rewrite',
    description: '强化开头钩子、叙事推进和口播节奏。',
    content:
      '任务模板：{{taskTemplateContent}}\n\n事实简稿：{{reviewedText}}\n\n改写强度：{{rewriteIntensity}}；叙事视角：{{narrativePov}}；额外要求：{{extraRequirements}}\n\n请改写成短视频口播稿：开头有反差，中段有转折，结尾有情绪落点。不要添加素材无法支持的细节。',
    isBuiltin: true,
    updatedAt,
    origin: 'system',
  },
  {
    id: 'builtin-cover',
    name: '封面信息',
    type: 'cover',
    description: '生成标题、副标题、摘要、标签和种子评论。',
    content:
      '最终口播稿：{{rewrittenCopy}}\n\n请生成适合短视频发布的封面标题、两条副标题、摘要、话题标签和种子评论。标题要短、有信息量，不夸大、不制造虚假冲突。',
    isBuiltin: true,
    updatedAt,
    origin: 'system',
  },
  {
    id: 'builtin-storyboard',
    name: '分镜分句',
    type: 'storyboard',
    description: '把口播稿拆成可配图、可配音的镜头句。',
    content:
      '最终口播稿：{{rewrittenCopy}}\n\n任务模板：{{taskTemplateContent}}\n\n请拆成连续分镜句。每个镜头只表达一个动作、场景或情绪，cap 适合字幕，descPrompt 可直接指导画面生成，durationMs 按句子长度估算。',
    isBuiltin: true,
    updatedAt,
    origin: 'system',
  },
  {
    id: 'builtin-image-prompt',
    name: '绘图提示词',
    type: 'image-prompt',
    description: '统一角色、镜头、场景、风格和负面提示词。',
    content:
      '分镜 JSON：{{scenesJson}}\n\n任务模板：{{taskTemplateContent}}\n\n画风：{{style}}；比例：{{ratio}}；主角策略：{{characterPolicy}}；参考图类型：{{referenceKind}}；骨架模块：{{step3SkeletonModules}}\n\n请先提取主体档案，再为每个镜头生成一致的中文绘图提示词和 negativePrompt。避免画面中出现字幕、水印、签名、UI、畸形肢体和不必要文字。',
    isBuiltin: true,
    updatedAt,
    origin: 'system',
  },
];

export const defaultCustomStyles: CustomStyle[] = [
  {
    id: 'black-white',
    name: '黑白摄影',
    tag: '纪实感',
    shortName: '黑白',
    prefix: '黑白纪实摄影，高对比光影，颗粒感，真实人物质感',
    suffix: '自然构图，电影级光线，真实细节',
    negativePrompt: '卡通，动漫，低质量，模糊，变形，水印，文字',
    allowColor: false,
    description: '适合人物传记和纪实叙事。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'photo-real',
    name: '写实彩色',
    tag: '质感胶片',
    shortName: '写实',
    prefix: '写实摄影，电影级布光，真实人物，清晰细节',
    suffix: '高质量，浅景深，真实色彩',
    negativePrompt: '卡通，油画，低质量，额外肢体，文字，水印',
    allowColor: true,
    description: '通用短视频分镜风格。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'oil-paint',
    name: '油画风格',
    tag: '印象写意',
    shortName: '油画',
    prefix: '油画质感，厚涂笔触，柔和自然光，人物和场景带有手工绘制的层次',
    suffix: '写意构图，丰富肌理，柔和色彩，画面有叙事感',
    negativePrompt: '照片写实，卡通，低质量，过度锐化，文字，水印，畸形肢体',
    allowColor: true,
    description: '适合书摘、知识类和情绪表达偏柔和的内容。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'modern-film',
    name: '现代电影',
    tag: '宽屏调色',
    shortName: '电影',
    prefix: '现代电影镜头，真实场景，宽屏构图，克制高级的电影调色',
    suffix: '自然表演，空间纵深，氛围光，电影级细节',
    negativePrompt: '卡通，插画，低质量，过曝，文字，水印，畸形肢体',
    allowColor: true,
    description: '适合情感、都市、通用叙事和剧情感较强的短视频。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'ancient-film',
    name: '古风电影',
    tag: '古代史诗',
    shortName: '古风',
    prefix: '古装电影质感，历史场景，细腻服饰，庄重光影',
    suffix: '电影构图，真实布景，古代建筑',
    negativePrompt: '现代物件，卡通，低质量，水印，文字',
    allowColor: true,
    description: '适合古代人物和文化内容。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'retro-film',
    name: '复古胶片',
    tag: '80年代闭达',
    shortName: '复古',
    prefix: '复古胶片摄影，80年代生活气息，暖色颗粒，街头纪实质感',
    suffix: '自然抓拍，真实环境光，胶片颗粒，怀旧但清晰',
    negativePrompt: '未来科技感，卡通，低质量，过度磨皮，文字，水印',
    allowColor: true,
    description: '适合美食探店、街角小店、城市烟火气和怀旧叙事。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'watercolor',
    name: '水彩治愈',
    tag: '柔和晕染',
    shortName: '水彩',
    prefix: '水彩插画，柔和晕染，温暖治愈，轻盈干净的童书画面',
    suffix: '纸张纹理，柔和边缘，清透色彩，温柔光线',
    negativePrompt: '写实照片，暗黑恐怖，强冲突，低质量，文字，水印',
    allowColor: true,
    description: '适合绘本故事、睡前故事和温柔治愈内容。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'magazine',
    name: '杂志插画',
    tag: '极简色块',
    shortName: '杂志',
    prefix: '现代杂志插画，极简色块，清晰主体，信息图式构图',
    suffix: '干净背景，平衡留白，高级配色，适合知识传播',
    negativePrompt: '复杂脏乱，恐怖，低质量，模糊，文字，水印',
    allowColor: true,
    description: '适合健康科普、图书拆解、电商卖点和知识说明。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'pixar-3d',
    name: '皮克斯 3D',
    tag: '动画质感',
    shortName: '3D',
    prefix: '高质量 3D 动画质感，友好的角色比例，柔和体积光，精致材质',
    suffix: '明亮色彩，电影动画构图，表情自然，细节丰富',
    negativePrompt: '恐怖，写实血腥，低质量，材质粗糙，文字，水印',
    allowColor: true,
    description: '适合轻松、有角色表现需求的动画化内容。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'ink',
    name: '中国水墨',
    tag: '文人意境',
    shortName: '水墨',
    prefix: '中国水墨画，留白构图，淡墨层次，传统文化意境',
    suffix: '宣纸纹理，水墨晕染，克制色彩，东方美学',
    negativePrompt: '现代霓虹，3D，低质量，脏乱背景，文字，水印',
    allowColor: true,
    description: '适合文化科普、传统器物、诗词意境和历史知识。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'folk',
    name: '民间故事工笔风',
    tag: '工笔叙事',
    shortName: '工笔',
    prefix: '民间故事工笔画风，乡土场景，细腻线描，传统叙事画面',
    suffix: '村镇山林，古朴服饰，层次清晰，带有传说感',
    negativePrompt: '现代城市，赛博朋克，低质量，卡通过度，文字，水印',
    allowColor: true,
    description: '适合民间传说、寓言、乡土叙事和古朴故事。',
    createdAt: updatedAt,
    updatedAt,
  },
  {
    id: 'ghibli',
    name: '吉卜力',
    tag: '治愈日漫',
    shortName: '吉卜力',
    prefix: '治愈日漫电影感，自然风景，温暖人物，柔和手绘动画质感',
    suffix: '明亮天空，丰富生活细节，温柔氛围，干净构图',
    negativePrompt: '真实照片，恐怖，低质量，过度商业海报感，文字，水印',
    allowColor: true,
    description: '适合治愈、成长、幻想和温暖日常故事。',
    createdAt: updatedAt,
    updatedAt,
  },
];

export const defaultAccount: AccountProfile = {
  displayName: '本地用户',
  email: 'local@storybound.replica',
  workspace: '默认工作区',
  avatarInitial: 'S',
  deviceId: 'local-device',
  balance: 0,
};

export const defaultActivation: ActivationState = {
  plan: 'trial',
  status: 'trial',
  code: '',
  expiresAt: null,
  message: '本地模拟试用模式：旧任务可继续执行，新任务不做真实付费限制。',
};

export const defaultUiPreferences: UiPreferences = {
  theme: 'dark',
  activeView: 'new-task',
};

export const defaultCreditTransactions: CreditTransaction[] = [
  {
    id: 1,
    type: 'system',
    amount: 0,
    balance: 0,
    taskId: null,
    description: '本地模拟积分，不参与真实扣费。',
    createdAt: updatedAt,
  },
];

export const defaultMinimaxCloneVoices: MinimaxCloneVoice[] = [];
