import type { HotBoardSourceAssessment } from './types';

export const HOT_BOARD_SOURCE_ASSESSMENTS: readonly HotBoardSourceAssessment[] = [
  {
    id: 'uapi',
    label: '全网热榜（UAPI）',
    url: 'https://uapis.cn/hotboard',
    coverage: '40+ 平台结构化榜单',
    suitability: 'connected',
    reason: '公开 JSON 接口，字段完整，适合作为中文综合热榜主源。',
  },
  {
    id: 'techmeme',
    label: 'Techmeme',
    url: 'https://www.techmeme.com',
    coverage: '全球科技与 AI 新闻',
    suitability: 'connected',
    reason: '公开 RSS 稳定，适合作为科技与 AI 的补充源。',
  },
  {
    id: 'anyknew',
    label: 'AnyKnew',
    url: 'https://www.anyknew.com',
    coverage: '中文多平台综合热榜',
    suitability: 'reference',
    reason: '覆盖面合适，但未确认稳定公开接口，保留为人工交叉核验。',
  },
  {
    id: 'tophub',
    label: '今日热榜',
    url: 'https://tophub.today',
    coverage: '中文多平台聚合',
    suitability: 'reference',
    reason: '选题覆盖合适，但当前可用性不稳定，暂不作为自动数据源。',
  },
  {
    id: 'newsnow',
    label: 'NewsNow',
    url: 'https://newsnow.busiyi.world',
    coverage: '多平台实时资讯',
    suitability: 'reference',
    reason: '聚合结构合适，但当前拒绝自动访问，不绕过站点访问控制。',
  },
  {
    id: 'rebang',
    label: '全站热榜',
    url: 'https://rebang.today',
    coverage: '中文多平台热搜',
    suitability: 'reference',
    reason: '页面可访问，但未确认稳定 JSON 或 RSS，保留为人工核验。',
  },
  {
    id: 'nowhots',
    label: '即时热点',
    url: 'https://nowhots.com',
    coverage: '中文实时热点汇总',
    suitability: 'reference',
    reason: '适合补充浏览，但没有可依赖的公开结构化接口。',
  },
  {
    id: 'sopilot',
    label: 'SoPilot',
    url: 'https://sopilot.net/zh/hot-tweets',
    coverage: 'X 平台热帖',
    suitability: 'excluded',
    reason: '单平台且核心数据依赖登录或动态请求，不适合作为综合热榜主源。',
  },
  {
    id: 'tl1',
    label: 'TL1',
    url: 'https://tl1.com',
    coverage: '中文热门推文聚合',
    suitability: 'excluded',
    reason: '当前无法获得有效响应，暂不接入生产数据流。',
  },
  {
    id: 'tameng',
    label: '糖果梦热榜',
    url: 'https://tameng.com',
    coverage: '垂直领域热搜与 RSS',
    suitability: 'excluded',
    reason: '当前无法获得有效响应，待站点恢复并确认接口后再评估。',
  },
];
