import type { DraftTemplate } from './types';

const noBorder = {
  color: '#000000',
  width: 0,
  alpha: 0,
};

const storyboundBorder = {
  color: '#000000',
  width: 40,
  alpha: 1,
};

const captionBase = {
  visible: true,
  x: 0,
  fontSize: 12,
  color: '#FFDE00',
  alpha: 1,
  border: noBorder,
  bold: false,
  underline: false,
  align: 1,
  letterSpacing: 0,
  lineSpacing: 0,
  maxCharsPerLine: 12,
  background: {
    color: '#000000',
    alpha: 0.5,
    roundRadius: 0.3,
  },
};

const titleBase = {
  visible: true,
  text: '主标题示例',
  x: 0,
  y: 0.04739583333333333,
  fontSize: 25,
  color: '#FFDE00',
  alpha: 1,
  bold: true,
  underline: true,
  align: 1,
  letterSpacing: 0,
  lineSpacing: 0,
  border: storyboundBorder,
};

const subtitleBase = {
  visible: true,
  text: '副标题示例文字',
  x: 0,
  y: -0.21666666666666667,
  fontSize: 12,
  color: '#FFFFFF',
  alpha: 1,
  bold: false,
  underline: false,
  align: 1,
  letterSpacing: 2,
  lineSpacing: 4,
  border: storyboundBorder,
};

const disclaimerBase = {
  visible: true,
  text: '图片由AI生成与网络下载\n科普视频，无不良引导',
  x: 0,
  y: -0.903125,
  fontSize: 8,
  color: '#FFFFFF',
  alpha: 0.26,
  bold: false,
  underline: false,
  align: 1,
  letterSpacing: 0,
  lineSpacing: 5,
  border: storyboundBorder,
};

const audioBase = {
  narrationVolume: 10,
  bgmVolume: 3,
  transitionType: '叠化',
  transitionDurationMs: 450,
  narrationFadeInMs: 80,
  narrationFadeOutMs: 80,
  bgmFadeInMs: 800,
  bgmFadeOutMs: 2000,
  filterType: '',
  videoEffectType: '',
  audioEffectType: '',
};

export const imageAnimations = [
  '无动画',
  '缩放',
  '缩放 II',
  '左拉镜',
  '右拉镜',
  '向左缩小',
  '向右缩小',
  '形变左缩',
  '形变右缩',
  '上下分割',
  '左右分割',
  '向左下降',
  '向右下降',
  '旋转缩小',
  '旋转上升',
  '翻转',
  '回弹伸缩',
  '滑滑梯',
  '滑滑梯 II',
  '四格滑动',
  '百叶窗',
  '百叶窗 II',
  '抖入放大',
  '三分割',
  '三分割 II',
  '上下分割 II',
  '上升旋转',
  '下降向右',
  '下降向左',
  '中间分割',
  '中间分割 II',
  '叠叠乐',
  '叠叠乐 II',
  '叠叠乐 III',
  '叠叠乐 IV',
  '叠叠乐 V',
  '叠叠乐 VI',
  '哈哈镜',
  '哈哈镜 II',
  '四格翻转',
  '四格转动',
  '四格转动 II',
  '夹心饼干',
  '夹心饼干 II',
  '小火车',
  '小火车 II',
  '小火车 III',
  '小火车 IV',
  '小陀螺',
  '小陀螺 II',
  '左右分割 II',
  '弹入旋转',
  '形变缩小',
  '悠悠球',
  '悠悠球 II',
  '手机',
  '手机 II',
  '手机 III',
  '扭曲拉伸',
  '拉伸扭曲',
  '放大弹动',
  '斜转',
  '斜转 II',
  '方片转动',
  '方片转动 II',
  '旋入晃动',
  '旋出渐隐',
  '旋转伸缩',
  '旋转回吸',
  '旋转降落',
  '晃动旋出',
  '水晶',
  '水晶 II',
  '波动滑出',
  '海盗船',
  '海盗船 II',
  '海盗船 III',
  '海盗船 IV',
  '滑入波动',
  '碎块滑动',
  '碎块滑动 II',
  '立方体',
  '立方体 II',
  '立方体 III',
  '立方体 IV',
  '立方体 V',
  '绕圈圈',
  '绕圈圈 II',
  '绕圈圈 III',
  '绕圈圈 IV',
  '缩小弹动',
  '缩小旋转',
  '缩小转出',
  '翻转 II',
  '翻转 III',
  '翻转 IV',
  '翻转 V',
  '翻转 VI',
  '荡秋千',
  '荡秋千 II',
  '转入转出',
  '转入转出 II',
  '转圈圈',
  '过山车',
  '过山车 II',
  '降落旋转',
  '魔方',
  '魔方 II',
  '分身',
  '分身 II',
  '动感摇晃 I',
  '动感摇晃 II',
  '四格滑动 II',
  '四格翻转 II',
  '回忆旋转',
  '坠落',
  '弹动冲屏',
  '波动吸收',
  '波动放大',
  '相框滑动',
  '红酒摇晃',
  '跳跳糖',
  '闪光放大',
  '闪光放大 II',
];

export const draftTemplates: DraftTemplate[] = [
  {
    id: 'default-portrait-9-16',
    name: '默认竖屏',
    isDefault: true,
    canvas: { width: 1080, height: 1920, ratio: '9:16', backgroundColor: '#000000', backgroundImage: '' },
    image: { visible: true, ratio: '9:16', fit: 'cover', top: 0, height: 1, animation: '缩放' },
    title: titleBase,
    subtitle: subtitleBase,
    caption: { ...captionBase, y: -0.21510416666666668 },
    disclaimer: disclaimerBase,
    audio: audioBase,
  },
  {
    id: 'builtin-portrait-4-3',
    name: '竖屏4:3',
    isDefault: true,
    canvas: { width: 1080, height: 1920, ratio: '9:16', backgroundColor: '#000000', backgroundImage: '' },
    image: { visible: true, ratio: '4:3', fit: 'cover', top: 0.2890625, height: 0.421875, animation: '缩放' },
    title: { ...titleBase, y: 0.8357783211083945, fontSize: 20, underline: false },
    subtitle: { ...subtitleBase, y: 0.5953125 },
    caption: { ...captionBase, y: -0.5572916666666666 },
    disclaimer: { ...disclaimerBase, y: -0.8141628912685337, alpha: 1 },
    audio: audioBase,
  },
  {
    id: 'builtin-landscape-16-9',
    name: '横屏16:9',
    isDefault: true,
    canvas: { width: 1920, height: 1080, ratio: '16:9', backgroundColor: '#000000', backgroundImage: '' },
    image: { visible: true, ratio: '16:9', fit: 'cover', top: 0, height: 1, animation: '缩放' },
    title: { ...titleBase, y: 0.12777777777777777, fontSize: 20, underline: false },
    subtitle: { ...subtitleBase, y: -0.43333333333333335, fontSize: 8 },
    caption: { ...captionBase, y: -0.6425925925925926, fontSize: 8 },
    disclaimer: {
      ...disclaimerBase,
      text: '图片由AI生成与网络下载 科普视频，无不良引导',
      y: -0.8787037037037037,
      fontSize: 5,
      alpha: 0.5,
    },
    audio: audioBase,
  },
];

export function getTemplate(id = 'default-portrait-9-16'): DraftTemplate {
  return draftTemplates.find((template) => template.id === id) ?? draftTemplates[0];
}

export function normalizeDraftTemplate(template: Partial<DraftTemplate>): DraftTemplate {
  const fallback = draftTemplates.find((item) => item.id === template.id) ?? draftTemplates[0];
  return {
    ...fallback,
    ...template,
    canvas: { ...fallback.canvas, ...template.canvas },
    image: { ...fallback.image, ...template.image },
    title: {
      ...fallback.title,
      ...template.title,
      x: finiteNumber(template.title?.x, fallback.title.x),
      y: finiteNumber(template.title?.y, fallback.title.y),
      alpha: finiteNumber(template.title?.alpha, fallback.title.alpha),
      bold: typeof template.title?.bold === 'boolean' ? template.title.bold : fallback.title.bold,
      underline: typeof template.title?.underline === 'boolean' ? template.title.underline : fallback.title.underline,
      align: finiteNumber(template.title?.align, fallback.title.align),
      letterSpacing: finiteNumber(template.title?.letterSpacing, fallback.title.letterSpacing),
      lineSpacing: finiteNumber(template.title?.lineSpacing, fallback.title.lineSpacing),
      border: normalizeTextBorder(template.title?.border, fallback.title.border),
    },
    subtitle: {
      ...fallback.subtitle,
      ...template.subtitle,
      x: finiteNumber(template.subtitle?.x, fallback.subtitle.x),
      y: finiteNumber(template.subtitle?.y, fallback.subtitle.y),
      text: finiteString(template.subtitle?.text, fallback.subtitle.text),
      alpha: finiteNumber(template.subtitle?.alpha, fallback.subtitle.alpha),
      bold: typeof template.subtitle?.bold === 'boolean' ? template.subtitle.bold : fallback.subtitle.bold,
      underline: typeof template.subtitle?.underline === 'boolean' ? template.subtitle.underline : fallback.subtitle.underline,
      align: finiteNumber(template.subtitle?.align, fallback.subtitle.align),
      letterSpacing: finiteNumber(template.subtitle?.letterSpacing, fallback.subtitle.letterSpacing),
      lineSpacing: finiteNumber(template.subtitle?.lineSpacing, fallback.subtitle.lineSpacing),
      border: normalizeTextBorder(template.subtitle?.border, fallback.subtitle.border),
    },
    caption: {
      ...fallback.caption,
      ...template.caption,
      x: finiteNumber(template.caption?.x, fallback.caption.x),
      y: finiteNumber(template.caption?.y, fallback.caption.y),
      border: normalizeTextBorder(template.caption?.border, fallback.caption.border),
      background: { ...fallback.caption.background, ...template.caption?.background },
    },
    disclaimer: {
      ...fallback.disclaimer,
      ...template.disclaimer,
      x: finiteNumber(template.disclaimer?.x, fallback.disclaimer.x),
      y: finiteNumber(template.disclaimer?.y, fallback.disclaimer.y),
      fontSize: finiteNumber(template.disclaimer?.fontSize, fallback.disclaimer.fontSize),
      color: finiteString(template.disclaimer?.color, fallback.disclaimer.color),
      alpha: finiteNumber(template.disclaimer?.alpha, fallback.disclaimer.alpha),
      bold: typeof template.disclaimer?.bold === 'boolean' ? template.disclaimer.bold : fallback.disclaimer.bold,
      underline: typeof template.disclaimer?.underline === 'boolean' ? template.disclaimer.underline : fallback.disclaimer.underline,
      align: finiteNumber(template.disclaimer?.align, fallback.disclaimer.align),
      letterSpacing: finiteNumber(template.disclaimer?.letterSpacing, fallback.disclaimer.letterSpacing),
      lineSpacing: finiteNumber(template.disclaimer?.lineSpacing, fallback.disclaimer.lineSpacing),
      border: normalizeTextBorder(template.disclaimer?.border, fallback.disclaimer.border),
    },
    audio: { ...fallback.audio, ...template.audio },
  };
}

function finiteNumber(value: unknown, fallback: number): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

function finiteString(value: unknown, fallback: string): string {
  return typeof value === 'string' && value.trim() ? value : fallback;
}

function normalizeTextBorder(value: unknown, fallback = noBorder): typeof noBorder {
  const input = value && typeof value === 'object' ? value as Partial<typeof noBorder> : {};
  return {
    color: finiteString(input.color, fallback.color),
    width: finiteNumber(input.width, fallback.width),
    alpha: finiteNumber(input.alpha, fallback.alpha),
  };
}
