// Source: https://www.suno-api.io/create/ (public style catalog, retrieved 2026-09-17).
// Keep every category entry, including tags listed in more than one category.
export interface MusicStyleTag { zh: string; en: string }
export interface MusicStyleCategory { id: string; label: string; tags: readonly MusicStyleTag[] }
export interface MusicStyleGroup { id: string; label: string; categories: readonly MusicStyleCategory[] }

export const MUSIC_STYLE_GROUPS: readonly MusicStyleGroup[] = [
  { id: "genre", label: "曲风", categories: [
    { id: "hot", label: "常用", tags: [
      {"zh":"流行","en":"Pop"},
      {"zh":"摇滚","en":"Rock"},
      {"zh":"电子","en":"Electronic"},
      {"zh":"嘻哈","en":"Hip-Hop"},
      {"zh":"节奏布鲁斯","en":"R&B"},
      {"zh":"乡村","en":"Country"},
      {"zh":"民谣","en":"Folk"},
      {"zh":"爵士","en":"Jazz"},
      {"zh":"古典","en":"Classical"},
      {"zh":"金属","en":"Metal"},
      {"zh":"国风","en":"Chinese Traditional Style"},
      {"zh":"朋克","en":"Punk"},
      {"zh":"灵魂乐","en":"Soul"},
      {"zh":"放克","en":"Funk"},
      {"zh":"迪斯科","en":"Disco"},
      {"zh":"舞曲","en":"Dance"},
      {"zh":"抒情歌","en":"Ballad"},
      {"zh":"福音音乐","en":"Gospel"},
      {"zh":"世界音乐","en":"World Music"},
      {"zh":"新世纪","en":"New Age"},
      {"zh":"氛围音乐","en":"Ambient"},
      {"zh":"雷鬼","en":"Reggae"},
      {"zh":"拉丁","en":"Latin"},
      {"zh":"布鲁斯","en":"Blues"},
    ] },
    { id: "pop", label: "流行", tags: [
      {"zh":"当代流行","en":"Contemporary Pop"},
      {"zh":"舞曲流行","en":"Dance Pop"},
      {"zh":"合成器流行","en":"Synth-Pop"},
      {"zh":"电子流行","en":"Electropop"},
      {"zh":"独立流行","en":"Indie Pop"},
      {"zh":"艺术流行","en":"Art Pop"},
      {"zh":"力量流行","en":"Power Pop"},
      {"zh":"巴洛克流行","en":"Baroque Pop"},
      {"zh":"卧室流行","en":"Bedroom Pop"},
      {"zh":"超流行","en":"Hyperpop"},
      {"zh":"精致流行","en":"Sophisti-Pop"},
      {"zh":"城市流行","en":"City Pop"},
      {"zh":"青少年流行","en":"Teen Pop"},
      {"zh":"泡泡糖流行","en":"Bubblegum Pop"},
      {"zh":"流行摇滚","en":"Pop Rock"},
      {"zh":"韩国流行","en":"K-Pop"},
      {"zh":"日本流行","en":"J-Pop"},
      {"zh":"阿拉伯流行","en":"Arabic Pop"},
      {"zh":"拉丁流行","en":"Latin Pop"},
      {"zh":"非洲流行","en":"Afropop"},
    ] },
    { id: "rock", label: "摇滚", tags: [
      {"zh":"经典摇滚","en":"Classic Rock"},
      {"zh":"硬摇滚","en":"Hard Rock"},
      {"zh":"另类摇滚","en":"Alternative Rock"},
      {"zh":"独立摇滚","en":"Indie Rock"},
      {"zh":"前卫摇滚","en":"Progressive Rock"},
      {"zh":"迷幻摇滚","en":"Psychedelic Rock"},
      {"zh":"车库摇滚","en":"Garage Rock"},
      {"zh":"后摇滚","en":"Post-Rock"},
      {"zh":"数学摇滚","en":"Math Rock"},
      {"zh":"自赏摇滚","en":"Shoegaze"},
      {"zh":"油渍摇滚","en":"Grunge"},
      {"zh":"情绪摇滚","en":"Emo"},
      {"zh":"工业摇滚","en":"Industrial Rock"},
      {"zh":"噪音摇滚","en":"Noise Rock"},
      {"zh":"艺术摇滚","en":"Art Rock"},
      {"zh":"华丽摇滚","en":"Glam Rock"},
      {"zh":"布鲁斯摇滚","en":"Blues Rock"},
      {"zh":"民谣摇滚","en":"Folk Rock"},
      {"zh":"流行摇滚","en":"Pop Rock"},
      {"zh":"朋克摇滚","en":"Punk Rock"},
      {"zh":"金属","en":"Metal"},
      {"zh":"南方摇滚","en":"Southern Rock"},
      {"zh":"泥浆摇滚","en":"Sludge Rock"},
      {"zh":"石人摇滚","en":"Stoner Rock"},
      {"zh":"太空摇滚","en":"Space Rock"},
      {"zh":"德国摇滚","en":"Krautrock"},
      {"zh":"滑板摇滚","en":"Skate Rock"},
    ] },
    { id: "electronic", label: "电子", tags: [
      {"zh":"电子舞曲","en":"EDM"},
      {"zh":"浩室","en":"House"},
      {"zh":"深度浩室","en":"Deep House"},
      {"zh":"渐进浩室","en":"Progressive House"},
      {"zh":"科技浩室","en":"Tech House"},
      {"zh":"贝斯浩室","en":"Bass House"},
      {"zh":"非洲浩室","en":"Afro House"},
      {"zh":"拉丁浩室","en":"Latin House"},
      {"zh":"科技舞曲","en":"Techno"},
      {"zh":"底特律铁克诺","en":"Detroit Techno"},
      {"zh":"极简铁克诺","en":"Minimal Techno"},
      {"zh":"旋律铁克诺","en":"Melodic Techno"},
      {"zh":"工业铁克诺","en":"Industrial Techno"},
      {"zh":"回响贝斯","en":"Dubstep"},
      {"zh":"旋律回响贝斯","en":"Melodic Dubstep"},
      {"zh":"鼓与贝斯","en":"Drum and Bass"},
      {"zh":"未来贝斯","en":"Future Bass"},
      {"zh":"迷幻舞曲","en":"Trance"},
      {"zh":"振奋出神","en":"Uplifting Trance"},
      {"zh":"迷幻出神","en":"Psytrance"},
      {"zh":"硬派舞曲","en":"Hardstyle"},
      {"zh":"硬核舞曲","en":"Hardcore Dance"},
      {"zh":"合成器浪潮","en":"Synthwave"},
      {"zh":"蒸汽波","en":"Vaporwave"},
      {"zh":"轻松浪潮","en":"Chillwave"},
      {"zh":"智能舞曲","en":"IDM"},
      {"zh":"故障音乐","en":"Glitch"},
      {"zh":"冯克","en":"Phonk"},
      {"zh":"迷幻嘻哈","en":"Psychedelic Hip-Hop"},
      {"zh":"工业","en":"Industrial"},
      {"zh":"氛围音乐","en":"Ambient"},
      {"zh":"冷调","en":"Chill"},
      {"zh":"慢节奏","en":"Downtempo"},
      {"zh":"高能量","en":"High Energy"},
      {"zh":"电子","en":"Electronic"},
    ] },
    { id: "hiphop", label: "嘻哈", tags: [
      {"zh":"说唱","en":"Rap"},
      {"zh":"陷阱说唱","en":"Trap"},
      {"zh":"低保真嘻哈","en":"Lo-Fi Hip-Hop"},
      {"zh":"爵士说唱","en":"Jazz Rap"},
      {"zh":"云说唱","en":"Cloud Rap"},
      {"zh":"钻孔说唱","en":"Drill"},
      {"zh":"英式说唱","en":"Grime"},
      {"zh":"砰啪嘻哈","en":"Boom Bap"},
      {"zh":"老派嘻哈","en":"Old School Hip-Hop"},
      {"zh":"另类嘻哈","en":"Alternative Hip-Hop"},
      {"zh":"地下嘻哈","en":"Underground Hip-Hop"},
      {"zh":"意识嘻哈","en":"Conscious Hip-Hop"},
      {"zh":"东海岸","en":"East Coast Hip-Hop"},
      {"zh":"西海岸","en":"West Coast Hip-Hop"},
      {"zh":"南方嘻哈","en":"Southern Hip-Hop"},
      {"zh":"冯克","en":"Phonk"},
    ] },
    { id: "rnb", label: "节奏布鲁斯与灵魂", tags: [
      {"zh":"节奏布鲁斯","en":"R&B"},
      {"zh":"当代节奏布鲁斯","en":"Contemporary R&B"},
      {"zh":"灵魂乐","en":"Soul"},
      {"zh":"新灵魂乐","en":"Neo-Soul"},
      {"zh":"放克","en":"Funk"},
      {"zh":"摩城","en":"Motown"},
      {"zh":"福音音乐","en":"Gospel"},
      {"zh":"爵士/灵魂","en":"Jazz Soul"},
    ] },
    { id: "country", label: "乡村", tags: [
      {"zh":"乡村","en":"Country"},
      {"zh":"乡村摇滚","en":"Country Rock"},
      {"zh":"蓝草","en":"Bluegrass"},
      {"zh":"美国民谣","en":"Americana"},
      {"zh":"酒吧乡村","en":"Honky Tonk"},
      {"zh":"另类乡村","en":"Alternative Country"},
    ] },
    { id: "folk", label: "民谣", tags: [
      {"zh":"民谣","en":"Folk"},
      {"zh":"独立民谣","en":"Indie Folk"},
      {"zh":"传统民谣","en":"Traditional Folk"},
      {"zh":"民谣摇滚","en":"Folk Rock"},
      {"zh":"凯尔特","en":"Celtic"},
      {"zh":"创作歌手","en":"Singer-Songwriter"},
      {"zh":"吟游诗人","en":"Troubadour"},
    ] },
    { id: "jazz", label: "爵士", tags: [
      {"zh":"摇摆爵士","en":"Swing Jazz"},
      {"zh":"大乐队爵士","en":"Big Band"},
      {"zh":"冷爵士","en":"Cool Jazz"},
      {"zh":"柔和爵士","en":"Smooth Jazz"},
      {"zh":"波萨诺瓦","en":"Bossa Nova"},
      {"zh":"拉丁爵士","en":"Latin Jazz"},
      {"zh":"比博普","en":"Bebop"},
      {"zh":"酸爵士","en":"Acid Jazz"},
      {"zh":"灵魂爵士","en":"Soul Jazz"},
      {"zh":"融合爵士","en":"Jazz Fusion"},
      {"zh":"爵士融合","en":"Fusion"},
      {"zh":"自由爵士","en":"Free Jazz"},
      {"zh":"先锋爵士","en":"Avant-Garde Jazz"},
    ] },
    { id: "classical", label: "古典", tags: [
      {"zh":"巴洛克","en":"Baroque"},
      {"zh":"古典主义","en":"Classical Period"},
      {"zh":"浪漫主义","en":"Romantic Period"},
      {"zh":"现代古典","en":"Modern Classical"},
      {"zh":"印象主义","en":"Impressionism"},
      {"zh":"极简主义","en":"Minimalism"},
      {"zh":"歌剧","en":"Opera"},
      {"zh":"室内乐","en":"Chamber Music"},
      {"zh":"交响乐","en":"Symphony"},
      {"zh":"管弦乐","en":"Orchestral"},
      {"zh":"古典电影音乐","en":"Classical Film Score"},
      {"zh":"中世纪电影音乐","en":"Medieval Film Score"},
    ] },
    { id: "metal", label: "金属", tags: [
      {"zh":"重金属","en":"Heavy Metal"},
      {"zh":"新金属","en":"Nu Metal"},
      {"zh":"鞭挞金属","en":"Thrash Metal"},
      {"zh":"死亡金属","en":"Death Metal"},
      {"zh":"黑金属","en":"Black Metal"},
      {"zh":"厄运金属","en":"Doom Metal"},
      {"zh":"力量金属","en":"Power Metal"},
      {"zh":"交响金属","en":"Symphonic Metal"},
      {"zh":"民谣金属","en":"Folk Metal"},
      {"zh":"金属核","en":"Metalcore"},
      {"zh":"死亡核","en":"Deathcore"},
    ] },
    { id: "chinese", label: "国风", tags: [
      {"zh":"国风","en":"Chinese Traditional Style"},
      {"zh":"古风","en":"Ancient Chinese Style"},
      {"zh":"国潮","en":"China-Chic"},
      {"zh":"诗意国风","en":"Poetic Chinese Style"},
      {"zh":"武侠","en":"Wuxia"},
      {"zh":"仙侠","en":"Xianxia"},
      {"zh":"禅意","en":"Zen"},
      {"zh":"山水意境","en":"Shanshui Ambience"},
      {"zh":"水墨意境","en":"Ink Wash Ambience"},
      {"zh":"唐风","en":"Tang Dynasty Style"},
      {"zh":"宋韵","en":"Song Dynasty Style"},
      {"zh":"汉风","en":"Han Dynasty Style"},
      {"zh":"宫廷风","en":"Imperial Court Style"},
      {"zh":"宫宴风","en":"Imperial Banquet Style"},
      {"zh":"庙会","en":"Temple Fair"},
      {"zh":"中国民歌","en":"Chinese Folk Song"},
      {"zh":"戏曲","en":"Chinese Opera"},
      {"zh":"京剧","en":"Peking Opera"},
      {"zh":"昆曲","en":"Kunqu"},
      {"zh":"越剧","en":"Yue Opera"},
      {"zh":"戏腔","en":"Opera Voice"},
      {"zh":"国乐合奏","en":"Chinese Orchestra"},
      {"zh":"中国传统器乐","en":"Chinese Traditional Instrumental"},
      {"zh":"民族室内乐","en":"Chinese Chamber Ensemble"},
      {"zh":"江南丝竹","en":"Jiangnan Sizhu"},
      {"zh":"丝竹","en":"Sizhu"},
      {"zh":"古琴","en":"Guqin"},
      {"zh":"古筝","en":"Guzheng"},
      {"zh":"琵琶","en":"Pipa"},
      {"zh":"二胡","en":"Erhu"},
      {"zh":"笛子","en":"Dizi"},
      {"zh":"箫","en":"Xiao"},
      {"zh":"唢呐","en":"Suona"},
      {"zh":"笙","en":"Sheng"},
      {"zh":"中国鼓","en":"Chinese Drums"},
    ] },
    { id: "latin", label: "拉丁", tags: [
      {"zh":"拉丁流行","en":"Latin Pop"},
      {"zh":"萨尔萨","en":"Salsa"},
      {"zh":"雷鬼顿","en":"Reggaeton"},
      {"zh":"探戈","en":"Tango"},
      {"zh":"弗拉门戈","en":"Flamenco"},
      {"zh":"拉丁摇滚","en":"Latin Rock"},
      {"zh":"弗约罗","en":"Forró"},
      {"zh":"梅伦格","en":"Merengue"},
      {"zh":"巴查塔","en":"Bachata"},
    ] },
    { id: "reggae", label: "雷鬼", tags: [
      {"zh":"雷鬼","en":"Reggae"},
      {"zh":"根源雷鬼","en":"Roots Reggae"},
      {"zh":"配音","en":"Dub"},
      {"zh":"斯卡","en":"Ska"},
      {"zh":"舞厅","en":"Dancehall"},
      {"zh":"雷鬼顿","en":"Reggaeton"},
    ] },
    { id: "world", label: "世界音乐", tags: [
      {"zh":"世界音乐","en":"World Music"},
      {"zh":"非洲音乐","en":"African Music"},
      {"zh":"非洲节奏","en":"African Rhythm"},
      {"zh":"亚洲音乐","en":"Asian Music"},
      {"zh":"中东音乐","en":"Middle Eastern Music"},
      {"zh":"美洲原住民音乐","en":"Native American Music"},
      {"zh":"旁遮普音乐","en":"Punjabi"},
      {"zh":"宝莱坞","en":"Bollywood"},
      {"zh":"演歌","en":"Enka"},
      {"zh":"拉格","en":"Raga"},
      {"zh":"凯尔特","en":"Celtic"},
      {"zh":"克莱兹梅尔","en":"Klezmer"},
      {"zh":"波尔卡","en":"Polka"},
      {"zh":"昆比亚","en":"Cumbia"},
      {"zh":"柴迪科","en":"Zydeco"},
      {"zh":"卡津","en":"Cajun"},
      {"zh":"太鼓","en":"Taiko"},
      {"zh":"三味线","en":"Shamisen"},
      {"zh":"筝","en":"Koto"},
      {"zh":"西塔琴","en":"Sitar"},
      {"zh":"塔布拉鼓","en":"Tabla"},
      {"zh":"古琴","en":"Guqin"},
      {"zh":"戏曲","en":"Chinese Opera"},
      {"zh":"江南丝竹","en":"Jiangnan Sizhu"},
    ] },
    { id: "blues", label: "布鲁斯", tags: [
      {"zh":"三角洲布鲁斯","en":"Delta Blues"},
      {"zh":"芝加哥布鲁斯","en":"Chicago Blues"},
      {"zh":"德州布鲁斯","en":"Texas Blues"},
      {"zh":"跳跃布鲁斯","en":"Jump Blues"},
      {"zh":"电声布鲁斯","en":"Electric Blues"},
      {"zh":"原声布鲁斯","en":"Acoustic Blues"},
      {"zh":"钢琴布鲁斯","en":"Piano Blues"},
      {"zh":"灵魂布鲁斯","en":"Soul Blues"},
      {"zh":"布鲁斯摇滚","en":"Blues Rock"},
    ] },
    { id: "funk", label: "放克", tags: [
      {"zh":"P-Funk","en":"P-Funk"},
      {"zh":"G-Funk","en":"G-Funk"},
      {"zh":"爵士放克","en":"Jazz Funk"},
      {"zh":"放克摇滚","en":"Funk Rock"},
      {"zh":"电子放克","en":"Electro Funk"},
      {"zh":"非洲放克","en":"Afro Funk"},
      {"zh":"放克灵魂","en":"Funk Soul"},
      {"zh":"布吉","en":"Boogie"},
      {"zh":"深度放克","en":"Deep Funk"},
    ] },
  ] },
  { id: "mood", label: "情绪与氛围", categories: [
    { id: "emotion", label: "情绪", tags: [
      {"zh":"开心","en":"Happy"},
      {"zh":"温暖","en":"Warm"},
      {"zh":"欢快","en":"Cheerful"},
      {"zh":"浪漫","en":"Romantic"},
      {"zh":"温柔","en":"Gentle"},
      {"zh":"松弛","en":"Relaxed"},
      {"zh":"平静","en":"Calm"},
      {"zh":"宁静","en":"Serene"},
      {"zh":"安详","en":"Peaceful"},
      {"zh":"充满活力","en":"Energetic"},
      {"zh":"热情","en":"Passionate"},
      {"zh":"振奋","en":"Uplifting"},
      {"zh":"鼓舞","en":"Inspiring"},
      {"zh":"希望感","en":"Hopeful"},
      {"zh":"自信","en":"Confident"},
      {"zh":"赋权","en":"Empowering"},
      {"zh":"胜利","en":"Triumphant"},
      {"zh":"狂喜","en":"Euphoric"},
      {"zh":"梦幻","en":"Dreamy"},
      {"zh":"空灵","en":"Ethereal"},
      {"zh":"奇幻","en":"Whimsical"},
      {"zh":"奇思妙想","en":"Quirky"},
      {"zh":"俏皮","en":"Playful"},
      {"zh":"怀旧","en":"Nostalgic"},
      {"zh":"感伤","en":"Sentimental"},
      {"zh":"悲伤","en":"Sad"},
      {"zh":"忧思","en":"Melancholic"},
      {"zh":"苦乐参半","en":"Bittersweet"},
      {"zh":"渴望","en":"Yearning"},
      {"zh":"孤独","en":"Lonely"},
      {"zh":"反思","en":"Reflective"},
      {"zh":"萦绕","en":"Haunting"},
      {"zh":"神秘","en":"Mysterious"},
      {"zh":"怪诞","en":"Eerie"},
      {"zh":"悬疑","en":"Suspenseful"},
      {"zh":"紧张","en":"Tense"},
      {"zh":"不安","en":"Anxious"},
      {"zh":"戏剧性","en":"Dramatic"},
      {"zh":"电影氛围","en":"Cinematic"},
      {"zh":"史诗","en":"Epic"},
      {"zh":"英雄感","en":"Heroic"},
      {"zh":"激进","en":"Aggressive"},
      {"zh":"冷峻","en":"Cold"},
      {"zh":"粗犷","en":"Rugged"},
      {"zh":"粗粝","en":"Gritty"},
      {"zh":"脆弱","en":"Fragile"},
      {"zh":"精致","en":"Polished"},
      {"zh":"奢华","en":"Luxurious"},
    ] },
    { id: "scene", label: "场景", tags: [
      {"zh":"夏日海滩","en":"Summer Beach"},
      {"zh":"日落海滩","en":"Sunset Beach"},
      {"zh":"海边漫步","en":"Seaside Walk"},
      {"zh":"雨夜","en":"Rainy Night"},
      {"zh":"雨窗","en":"Rain on Window"},
      {"zh":"雪天","en":"Snowy Day"},
      {"zh":"冬雪","en":"Winter Snow"},
      {"zh":"春雨","en":"Spring Rain"},
      {"zh":"秋叶","en":"Autumn Leaves"},
      {"zh":"星夜","en":"Starry Night"},
      {"zh":"日出","en":"Sunrise"},
      {"zh":"日落","en":"Sunset"},
      {"zh":"黎明","en":"Dawn"},
      {"zh":"午夜","en":"Midnight"},
      {"zh":"深夜驾驶","en":"Late Night Drive"},
      {"zh":"咖啡厅","en":"Café"},
      {"zh":"夜店","en":"Nightclub"},
      {"zh":"图书馆","en":"Library"},
      {"zh":"花园","en":"Garden"},
      {"zh":"炉火边","en":"Fireside"},
      {"zh":"森林","en":"Forest"},
      {"zh":"山峰","en":"Mountains"},
      {"zh":"乡村","en":"Countryside"},
      {"zh":"城市街道","en":"City Streets"},
      {"zh":"旅行","en":"Travel"},
      {"zh":"公路旅行","en":"Road Trip"},
      {"zh":"火车旅行","en":"Train Ride"},
      {"zh":"飞机上","en":"On a Plane"},
      {"zh":"飞行","en":"Flying"},
      {"zh":"通勤","en":"Commute"},
      {"zh":"驾驶","en":"Driving"},
      {"zh":"步行","en":"Walking"},
      {"zh":"骑行","en":"Cycling"},
      {"zh":"露营","en":"Camping"},
      {"zh":"聚会","en":"Party"},
      {"zh":"婚礼","en":"Wedding"},
      {"zh":"毕业","en":"Graduation"},
      {"zh":"节日","en":"Festival"},
      {"zh":"回家","en":"Homecoming"},
      {"zh":"健身","en":"Workout"},
      {"zh":"水疗","en":"Spa"},
      {"zh":"冥想","en":"Meditation"},
      {"zh":"学习","en":"Study"},
      {"zh":"阅读","en":"Reading"},
      {"zh":"编程","en":"Coding"},
      {"zh":"游戏","en":"Gaming"},
      {"zh":"烹饪","en":"Cooking"},
      {"zh":"购物","en":"Shopping"},
      {"zh":"电梯","en":"Elevator"},
    ] },
    { id: "tempo", label: "速度与节奏", tags: [
      {"zh":"极慢","en":"Very Slow"},
      {"zh":"慢","en":"Slow"},
      {"zh":"中慢","en":"Medium Slow"},
      {"zh":"中速","en":"Medium"},
      {"zh":"中快","en":"Medium Fast"},
      {"zh":"快","en":"Fast"},
      {"zh":"极快","en":"Very Fast"},
      {"zh":"极速","en":"Presto"},
      {"zh":"半速","en":"Half Time"},
      {"zh":"倍速","en":"Double Time"},
      {"zh":"渐快","en":"Accelerando"},
      {"zh":"渐慢","en":"Ritardando"},
      {"zh":"稳定律动","en":"Steady Groove"},
      {"zh":"分解段","en":"Breakdown"},
      {"zh":"爆点","en":"Drop"},
    ] },
    { id: "instrument", label: "乐器", tags: [
      {"zh":"钢琴","en":"Piano"},
      {"zh":"木吉他","en":"Acoustic Guitar"},
      {"zh":"电吉他","en":"Electric Guitar"},
      {"zh":"贝斯","en":"Bass"},
      {"zh":"架子鼓","en":"Drum Kit"},
      {"zh":"打击乐","en":"Percussion"},
      {"zh":"合成器","en":"Synthesizer"},
      {"zh":"弦乐","en":"Strings"},
      {"zh":"小提琴","en":"Violin"},
      {"zh":"大提琴","en":"Cello"},
      {"zh":"竖琴","en":"Harp"},
      {"zh":"管弦乐队","en":"Orchestra"},
      {"zh":"铜管乐","en":"Brass"},
      {"zh":"小号","en":"Trumpet"},
      {"zh":"长号","en":"Trombone"},
      {"zh":"木管乐","en":"Woodwinds"},
      {"zh":"长笛","en":"Flute"},
      {"zh":"单簧管","en":"Clarinet"},
      {"zh":"双簧管","en":"Oboe"},
      {"zh":"萨克斯","en":"Saxophone"},
      {"zh":"口琴","en":"Harmonica"},
      {"zh":"手风琴","en":"Accordion"},
      {"zh":"风笛","en":"Bagpipes"},
      {"zh":"班卓琴","en":"Banjo"},
      {"zh":"曼陀林","en":"Mandolin"},
      {"zh":"尤克里里","en":"Ukulele"},
      {"zh":"二胡","en":"Erhu"},
      {"zh":"古筝","en":"Guzheng"},
      {"zh":"琵琶","en":"Pipa"},
      {"zh":"笛子","en":"Dizi"},
    ] },
  ] },
  { id: "vocal", label: "人声与语言", categories: [
    { id: "singing", label: "唱法", tags: [
      {"zh":"流行唱法","en":"Pop Singing"},
      {"zh":"摇滚唱法","en":"Rock Singing"},
      {"zh":"爵士唱法","en":"Jazz Singing"},
      {"zh":"R&B唱法","en":"R&B Vocals"},
      {"zh":"乡村唱法","en":"Country Vocals"},
      {"zh":"民谣唱法","en":"Folk Vocals"},
      {"zh":"嘻哈说唱","en":"Hip-Hop Flow"},
      {"zh":"歌剧唱法","en":"Operatic"},
      {"zh":"金属嘶吼","en":"Screamed Vocals"},
      {"zh":"假声","en":"Falsetto"},
      {"zh":"强声","en":"Belting"},
      {"zh":"低吟","en":"Crooning"},
      {"zh":"念白","en":"Spoken Word"},
    ] },
    { id: "language", label: "语言", tags: [
      {"zh":"国语","en":"Mandarin"},
      {"zh":"粤语","en":"Cantonese"},
      {"zh":"闽南语","en":"Hokkien"},
      {"zh":"日语","en":"Japanese"},
      {"zh":"韩语","en":"Korean"},
      {"zh":"越南语","en":"Vietnamese"},
      {"zh":"泰语","en":"Thai"},
      {"zh":"印尼语","en":"Indonesian"},
      {"zh":"马来语","en":"Malay"},
      {"zh":"菲律宾语","en":"Filipino"},
      {"zh":"美式英语","en":"American English"},
      {"zh":"英式英语","en":"British English"},
      {"zh":"西班牙语","en":"Spanish"},
      {"zh":"法语","en":"French"},
      {"zh":"德语","en":"German"},
      {"zh":"意大利语","en":"Italian"},
      {"zh":"葡萄牙语","en":"Portuguese"},
      {"zh":"俄语","en":"Russian"},
      {"zh":"荷兰语","en":"Dutch"},
      {"zh":"瑞典语","en":"Swedish"},
      {"zh":"波兰语","en":"Polish"},
      {"zh":"希腊语","en":"Greek"},
      {"zh":"拉丁语","en":"Latin"},
      {"zh":"印地语","en":"Hindi"},
      {"zh":"阿拉伯语","en":"Arabic"},
      {"zh":"希伯来语","en":"Hebrew"},
      {"zh":"土耳其语","en":"Turkish"},
    ] },
    { id: "harmony", label: "和声编排", tags: [
      {"zh":"齐唱","en":"Unison"},
      {"zh":"和声","en":"Harmonies"},
      {"zh":"对位","en":"Counterpoint"},
      {"zh":"呼应","en":"Call and Response"},
      {"zh":"叠唱","en":"Layered Vocals"},
      {"zh":"合唱","en":"Choir"},
      {"zh":"格里高利圣咏","en":"Gregorian Chant"},
    ] },
  ] },
  { id: "ensemble", label: "编制与演奏", categories: [
    { id: "voice-form", label: "人声形式", tags: [
      {"zh":"男声","en":"Male Vocals"},
      {"zh":"女声","en":"Female Vocals"},
      {"zh":"双声","en":"Duet Vocals"},
      {"zh":"群声","en":"Group Vocals"},
      {"zh":"主唱","en":"Lead Vocals"},
      {"zh":"和声","en":"Backing Vocals"},
    ] },
    { id: "instrument-form", label: "器乐形式", tags: [
      {"zh":"纯器乐","en":"Instrumental"},
      {"zh":"无伴奏合唱","en":"A Cappella"},
      {"zh":"独奏乐器","en":"Solo Instrument"},
      {"zh":"室内乐团","en":"Chamber Ensemble"},
      {"zh":"交响乐团","en":"Symphony Orchestra"},
    ] },
    { id: "scale", label: "表演规模", tags: [
      {"zh":"独奏/独唱","en":"Solo"},
      {"zh":"二重奏","en":"Duet"},
      {"zh":"三重奏","en":"Trio"},
      {"zh":"四重奏","en":"Quartet"},
      {"zh":"室内乐","en":"Chamber Music"},
      {"zh":"乐队","en":"Band"},
      {"zh":"管弦乐团","en":"Orchestra"},
      {"zh":"合唱团","en":"Choir"},
      {"zh":"大乐队","en":"Big Band"},
    ] },
  ] },
  { id: "rhythm", label: "节奏与曲式", categories: [
    { id: "meter", label: "拍号", tags: [
      {"zh":"4/4 常用拍","en":"4/4 Time"},
      {"zh":"3/4 华尔兹","en":"3/4 Waltz"},
      {"zh":"6/8 摇摆拍","en":"6/8 Time"},
      {"zh":"2/4 行进拍","en":"2/4 March"},
      {"zh":"5/4 非对称","en":"5/4 Time"},
      {"zh":"7/8 复杂拍","en":"7/8 Time"},
      {"zh":"9/8 复合拍","en":"9/8 Time"},
      {"zh":"12/8 复合摇摆","en":"12/8 Time"},
      {"zh":"2/2 Cut Time","en":"2/2 Cut Time"},
      {"zh":"3/8 轻快拍","en":"3/8 Time"},
      {"zh":"6/4 宽广拍","en":"6/4 Time"},
    ] },
    { id: "groove", label: "节奏型", tags: [
      {"zh":"均分节奏","en":"Even Rhythm"},
      {"zh":"切分节奏","en":"Syncopation"},
      {"zh":"三连音","en":"Triplets"},
      {"zh":"五连音","en":"Quintuplets"},
      {"zh":"七连音","en":"Septuplets"},
      {"zh":"摇摆","en":"Swing"},
      {"zh":"曳步","en":"Shuffle"},
      {"zh":"单拍子","en":"Simple Meter"},
      {"zh":"复拍子","en":"Compound Meter"},
      {"zh":"复节奏","en":"Polyrhythm"},
    ] },
    { id: "harmony-complexity", label: "和声", tags: [
      {"zh":"三和弦","en":"Triads"},
      {"zh":"七和弦","en":"Seventh Chords"},
      {"zh":"九和弦","en":"Ninth Chords"},
      {"zh":"十一和弦","en":"Eleventh Chords"},
      {"zh":"十三和弦","en":"Thirteenth Chords"},
      {"zh":"扩展和弦","en":"Extended Chords"},
      {"zh":"变化和弦","en":"Altered Chords"},
      {"zh":"挂留和弦","en":"Suspended Chords"},
      {"zh":"强力和弦","en":"Power Chords"},
      {"zh":"开放和弦","en":"Open Chords"},
    ] },
    { id: "melody", label: "旋律", tags: [
      {"zh":"流畅的","en":"Flowing"},
      {"zh":"跳跃的","en":"Leaping"},
      {"zh":"级进的","en":"Stepwise"},
      {"zh":"断奏的","en":"Staccato"},
      {"zh":"连奏的","en":"Legato"},
      {"zh":"连续的","en":"Continuous"},
      {"zh":"短句","en":"Short Phrases"},
      {"zh":"长句","en":"Long Phrases"},
      {"zh":"琶音的","en":"Arpeggiated"},
      {"zh":"半音的","en":"Chromatic"},
    ] },
    { id: "form", label: "曲式", tags: [
      {"zh":"主歌-副歌","en":"Verse-Chorus"},
      {"zh":"主歌-副歌-桥段","en":"Verse-Chorus-Bridge"},
      {"zh":"AABA结构","en":"AABA Form"},
      {"zh":"ABAB结构","en":"ABAB Form"},
      {"zh":"ABAC结构","en":"ABAC Form"},
      {"zh":"二部曲式","en":"Binary Form"},
      {"zh":"三部曲式","en":"Ternary Form"},
      {"zh":"通谱体","en":"Through-Composed"},
      {"zh":"分节歌","en":"Strophic"},
      {"zh":"12小节布鲁斯","en":"12-Bar Blues"},
      {"zh":"16小节","en":"16-Bar Form"},
      {"zh":"奏鸣曲式","en":"Sonata Form"},
      {"zh":"回旋曲式","en":"Rondo Form"},
      {"zh":"变奏曲式","en":"Variation Form"},
    ] },
  ] },
  { id: "fx", label: "音效与处理", categories: [
    { id: "space", label: "空间", tags: [
      {"zh":"混响","en":"Reverb"},
      {"zh":"延迟","en":"Delay"},
      {"zh":"回声","en":"Echo"},
      {"zh":"合唱效果","en":"Chorus"},
      {"zh":"镶边","en":"Flanger"},
      {"zh":"相位","en":"Phaser"},
      {"zh":"颤音（幅度）","en":"Tremolo"},
      {"zh":"颤音（音高）","en":"Vibrato"},
    ] },
    { id: "dynamics", label: "动态", tags: [
      {"zh":"压缩","en":"Compression"},
      {"zh":"限制","en":"Limiting"},
      {"zh":"扩展","en":"Expansion"},
      {"zh":"门限","en":"Gating"},
    ] },
    { id: "drive", label: "失真", tags: [
      {"zh":"失真","en":"Distortion"},
      {"zh":"过载","en":"Overdrive"},
      {"zh":"法兹","en":"Fuzz"},
      {"zh":"饱和","en":"Saturation"},
      {"zh":"比特破碎","en":"Bitcrush"},
    ] },
    { id: "filter", label: "滤波", tags: [
      {"zh":"低通滤波","en":"Low-Pass Filter"},
      {"zh":"高通滤波","en":"High-Pass Filter"},
      {"zh":"带通滤波","en":"Band-Pass Filter"},
      {"zh":"陷波滤波","en":"Notch Filter"},
      {"zh":"共振滤波","en":"Resonant Filter"},
    ] },
    { id: "modulation", label: "调制", tags: [
      {"zh":"环形调制","en":"Ring Mod"},
      {"zh":"移频","en":"Frequency Shift"},
      {"zh":"移调","en":"Pitch Shift"},
      {"zh":"时间拉伸","en":"Time Stretch"},
      {"zh":"粒子合成","en":"Granular Synthesis"},
    ] },
    { id: "special", label: "特殊", tags: [
      {"zh":"倒放","en":"Reversed"},
      {"zh":"故障","en":"Glitch"},
      {"zh":"口吃","en":"Stutter"},
      {"zh":"磁带停止","en":"Tape Stop"},
      {"zh":"黑胶噪点","en":"Vinyl Noise"},
      {"zh":"低保真效果","en":"Lo-Fi Effect"},
    ] },
  ] },
  { id: "production", label: "制作与音质", categories: [
    { id: "fidelity", label: "音质风格", tags: [
      {"zh":"低保真","en":"Lo-Fi"},
      {"zh":"高保真","en":"Hi-Fi"},
      {"zh":"模拟温暖","en":"Analog Warmth"},
      {"zh":"数字干净","en":"Digital Clean"},
      {"zh":"压缩感","en":"Compressed"},
      {"zh":"动态感","en":"Dynamic"},
      {"zh":"原始","en":"Raw"},
      {"zh":"精致","en":"Polished"},
    ] },
    { id: "recording", label: "录音类型", tags: [
      {"zh":"录音室录制","en":"Studio Recording"},
      {"zh":"现场录制","en":"Live Recording"},
      {"zh":"实地录音","en":"Field Recording"},
      {"zh":"原声小场录制","en":"Small Room Acoustic"},
      {"zh":"不插电","en":"Unplugged"},
      {"zh":"小样","en":"Demo"},
      {"zh":"盗版录音","en":"Bootleg"},
    ] },
    { id: "ambience", label: "空间感", tags: [
      {"zh":"干声","en":"Dry"},
      {"zh":"湿声","en":"Wet"},
      {"zh":"亲密","en":"Intimate"},
      {"zh":"宽广","en":"Wide"},
      {"zh":"房间感","en":"Room Ambience"},
      {"zh":"竞技场","en":"Arena"},
      {"zh":"大教堂","en":"Cathedral"},
      {"zh":"户外","en":"Outdoor"},
      {"zh":"地下","en":"Underground"},
      {"zh":"洞穴感","en":"Cavernous"},
    ] },
  ] },
  { id: "usage", label: "使用场景", categories: [
    { id: "visual", label: "影视媒体", tags: [
      {"zh":"电影配乐","en":"Film Score"},
      {"zh":"预告片音乐","en":"Trailer Music"},
      {"zh":"游戏BGM","en":"Game BGM"},
      {"zh":"动漫主题曲","en":"Anime Theme"},
      {"zh":"纪录片","en":"Documentary"},
      {"zh":"电视节目","en":"TV Show"},
      {"zh":"广告","en":"Commercial"},
    ] },
    { id: "content", label: "内容类型", tags: [
      {"zh":"播客片头","en":"Podcast Intro"},
      {"zh":"有声书","en":"Audiobook"},
      {"zh":"ASMR","en":"ASMR"},
      {"zh":"音效","en":"Sound Effect"},
      {"zh":"拟音","en":"Foley"},
      {"zh":"广告歌","en":"Jingle"},
      {"zh":"铃声","en":"Ringtone"},
    ] },
  ] },
  { id: "era", label: "年代与时期", categories: [
    { id: "period-style", label: "时期风格", tags: [
      {"zh":"复古","en":"Retro"},
      {"zh":"怀旧","en":"Vintage"},
      {"zh":"怀旧感","en":"Nostalgic"},
      {"zh":"经典","en":"Classic"},
      {"zh":"黄金时代","en":"Golden Era"},
      {"zh":"现代","en":"Modern"},
      {"zh":"当代","en":"Contemporary"},
      {"zh":"未来感","en":"Futuristic"},
      {"zh":"永恒","en":"Timeless"},
    ] },
    { id: "decade", label: "具体年代", tags: [
      {"zh":"1920年代","en":"1920s"},
      {"zh":"1930年代","en":"1930s"},
      {"zh":"1940年代","en":"1940s"},
      {"zh":"1950年代","en":"1950s"},
      {"zh":"1960年代","en":"1960s"},
      {"zh":"1970年代","en":"1970s"},
      {"zh":"1980年代","en":"1980s"},
      {"zh":"1990年代","en":"1990s"},
      {"zh":"2000年代","en":"2000s"},
      {"zh":"2010年代","en":"2010s"},
      {"zh":"2020年代","en":"2020s"},
    ] },
    { id: "history", label: "历史风格", tags: [
      {"zh":"中世纪","en":"Medieval"},
      {"zh":"文艺复兴","en":"Renaissance"},
      {"zh":"巴洛克","en":"Baroque"},
      {"zh":"维多利亚","en":"Victorian"},
      {"zh":"咆哮20年代","en":"Roaring Twenties"},
      {"zh":"千禧年","en":"Y2K"},
    ] },
  ] },
];
