import { useEffect, useRef, useState } from 'react';
import type { StoryDreamApi } from '../../shared/storydream-api';
import type { MusicEnhancedRequest, MusicEnhancedJob } from '../../shared/music-enhanced';
import { Button } from '../../ui';
export function MusicEnhancedPanel({api,audioPath,title,configured,onLibraryChanged,onBusyChange}:{api:StoryDreamApi;audioPath:string;title:string;configured:boolean;onLibraryChanged:()=>void;onBusyChange:(busy:boolean)=>void}) {
  const [jobs,setJobs]=useState<MusicEnhancedJob[]>([]);const [pendingAction,setPendingAction]=useState('');const [error,setError]=useState('');const lock=useRef(false);const mounted=useRef(false);
  useEffect(()=>{mounted.current=true;void loadJobs();return()=>{mounted.current=false;};},[]);
  async function loadJobs(){try{const next=await api.musicLabEnhanced({action:'list'});if(mounted.current)setJobs(next);}catch(cause){if(mounted.current)setError(cause instanceof Error?cause.message:String(cause));}}
  async function performEnhanced(input:MusicEnhancedRequest){if(lock.current)return;lock.current=true;setPendingAction(input.action);onBusyChange(true);setError('');try{const next=await api.musicLabEnhanced(input);if(mounted.current){setJobs(next);onLibraryChanged();}}catch(cause){if(mounted.current)setError(cause instanceof Error?cause.message:String(cause));}finally{lock.current=false;if(mounted.current){setPendingAction('');onBusyChange(false);}}}
  return <div className="music-lab__operation-form"><p className="music-lab__hint">强化上传会预扣 ¥10.00 / 次，最大 80 MB。任务失败或仍在排队时成功取消，按服务规则退款。</p><Button variant="primary" disabled={!!pendingAction || !configured || !audioPath} onClick={()=>void performEnhanced({action:'submit',audioPath,title})}>{pendingAction==='submit'?'提交中…':'强化上传 · ¥10.00'}</Button><section><h4>强化上传任务</h4><Button density="compact" disabled={!!pendingAction} onClick={()=>void loadJobs()}>刷新上传记录</Button>{!jobs.length&&<p className="music-lab__hint">还没有强化上传任务。</p>}{jobs.map((job)=><div key={job.id} className="music-lab__voice-job"><strong>{job.title}</strong><span>{job.stage||job.status}{job.progress?` · ${job.progress}%`:''}</span><Button density="compact" disabled={!!pendingAction||!configured||!job.taskId} onClick={()=>void performEnhanced({action:'poll',id:job.id})}>查询进度</Button><Button density="compact" disabled={!!pendingAction||!configured||job.status!=='queued'} onClick={()=>void performEnhanced({action:'cancel',id:job.id})}>取消排队任务</Button>{job.error&&<p className="music-lab__error">{job.error}</p>}</div>)}</section>{error&&<p className="music-lab__error" role="alert">{error}</p>}</div>;
}
